In [2]:
import pandas as pd 
import requests
state_list=["https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-AL-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-AK-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-AZ-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-AR-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-CA-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-CO-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-CT-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-DE-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-DC-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-ENC-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-ESC-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-FL-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-GA-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-HI-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-ID-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-IL-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-IN-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-IA-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-KS-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-KY-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-LA-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-ME-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-MD-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-MA-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-MI-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-MAT-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-MN-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-MS-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-MO-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-MT-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-MTN-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-NE-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-NV-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-NEW-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-NH-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-NJ-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-NM-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-NY-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-NC-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-ND-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-OH-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-OK-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-OR-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-PCC-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-PCN-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-PA-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-RI-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-SAT-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-SC-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-SD-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-TN-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-TX-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-US-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-UT-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-VT-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-VA-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-WA-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-WNC-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-WSC-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-WV-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-WI-99.M",
"https://www.eia.gov/opendata/qb.php?category=1718408&sdid=ELEC.GEN.TSN-WY-99.M"]
print("done")

done

In [3]:
raw={}
df={}
for i in range(0,len(state_list)):
    raw[i]=pd.read_html(state_list[i])
    df[i]=list(raw[i])
    df[i]=pd.DataFrame(df[i][0])
    print("done")
print("wow done")

done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
wow done

In [5]:
frames=[df[i] for i in range(0,len(state_list))]
result=pd.concat(frames)
print("done")

done

In [6]:
result

,Series Name,Period,Frequency,Value,Units
0,Net generation : all solar : Alabama : all sec...,201707,M,null,thousand megawatthours
1,Net generation : all solar : Alabama : all sec...,201706,M,null,thousand megawatthours
2,Net generation : all solar : Alabama : all sec...,201705,M,null,thousand megawatthours
3,Net generation : all solar : Alabama : all sec...,201704,M,null,thousand megawatthours
4,Net generation : all solar : Alabama : all sec...,201703,M,null,thousand megawatthours
5,Net generation : all solar : Alabama : all sec...,201702,M,null,thousand megawatthours
6,Net generation : all solar : Alabama : all sec...,201701,M,null,thousand megawatthours
7,Net generation : all solar : Alabama : all sec...,201612,M,7.0739,thousand megawatthours
8,Net generation : all solar : Alabama : all sec...,201611,M,13.39891,thousand megawatthours
9,Net generation : all solar : Alabama : all sec...,201610,M,11.1177,thousand megawatthours
10,Net generation : all solar : Alabama : all sec...,201609,M,0.79974,thousand megawatthours
11,Net generation : all solar : Alabama : all sec...,201608,M,0.38276,thousand megawatthours
12,Net generation : all solar : Alabama : all sec...,201607,M,0.38958,thousand megawatthours
13,Net generation : all solar : Alabama : all sec...,201606,M,0.38994,thousand megawatthours
14,Net generation : all solar : Alabama : all sec...,201605,M,0.39375,thousand megawatthours
15,Net generation : all solar : Alabama : all sec...,201604,M,0.36158,thousand megawatthours
16,Net generation : all solar : Alabama : all sec...,201603,M,0.32967,thousand megawatthours
17,Net generation : all solar : Alabama : all sec...,201602,M,0.25567,thousand megawatthours
18,Net generation : all solar : Alabama : all sec...,201601,M,0.23305,thousand megawatthours
19,Net generation : all solar : Alabama : all sec...,201512,M,0.1879,thousand megawatthours
20,Net generation : all solar : Alabama : all sec...,201511,M,0.21325,thousand megawatthours
21,Net generation : all solar : Alabama : all sec...,201510,M,0.25407,thousand megawatthours
22,Net generation : all solar : Alabama : all sec...,201509,M,0.2735,thousand megawatthours
23,Net generation : all solar : Alabama : all sec...,201508,M,0.31753,thousand megawatthours
24,Net generation : all solar : Alabama : all sec...,201507,M,0.32087,thousand megawatthours
25,Net generation : all solar : Alabama : all sec...,201506,M,0.32517,thousand megawatthours
26,Net generation : all solar : Alabama : all sec...,201505,M,0.32984,thousand megawatthours
27,Net generation : all solar : Alabama : all sec...,201504,M,0.30461,thousand megawatthours
28,Net generation : all solar : Alabama : all sec...,201503,M,0.27815,thousand megawatthours
29,Net generation : all solar : Alabama : all sec...,201502,M,0.2094,thousand megawatthours
...,...,...,...,...,...
13,Net generation : all solar : Wyoming : all sec...,201606,M,0.3603,thousand megawatthours
14,Net generation : all solar : Wyoming : all sec...,201605,M,0.35147,thousand megawatthours
15,Net generation : all solar : Wyoming : all sec...,201604,M,0.31348,thousand megawatthours
16,Net generation : all solar : Wyoming : all sec...,201603,M,0.26792,thousand megawatthours
17,Net generation : all solar : Wyoming : all sec...,201602,M,0.19312,thousand megawatthours
18,Net generation : all solar : Wyoming : all sec...,201601,M,0.15301,thousand megawatthours
19,Net generation : all solar : Wyoming : all sec...,201512,M,null,thousand megawatthours
20,Net generation : all solar : Wyoming : all sec...,201511,M,null,thousand megawatthours
21,Net generation : all solar : Wyoming : all sec...,201510,M,0.24776,thousand megawatthours
22,Net generation : all solar : Wyoming : all sec...,201509,M,0.27841,thousand megawatthours
23,Net generation : all solar : Wyoming : all sec...,201508,M,0.28873,thousand megawatthours
24,Net generation : all solar : Wyoming : all sec...,201507,M,0.30105,thousand megawatthours
25,Net generation : all solar : Wyoming : all sec...,201506,M,0.28413,thousand megawatthours
26,Net generation : all solar : Wyoming : all sec...,201505,M,0.27602,thousand megawatthours
27,Net generation : all solar : Wyoming : all sec...,201504,M,0.24717,thousand megawatthours
28,Net generation : all solar : Wyoming : all sec...,201503,M,0.21351,thousand megawatthours
29,Net generation : all solar : Wyoming : all sec...,201502,M,0.14731,thousand megawatthours
30,Net generation : all solar : Wyoming : all sec...,201501,M,0.12565,thousand megawatthours
31,Net generation : all solar : Wyoming : all sec...,201412,M,0.12633,thousand megawatthours
32,Net generation : all solar : Wyoming : all sec...,201411,M,0.15428,thousand megawatthours
33,Net generation : all solar : Wyoming : all sec...,201410,M,0.20982,thousand megawatthours
34,Net generation : all solar : Wyoming : all sec...,201409,M,0.23586,thousand megawatthours
35,Net generation : all solar : Wyoming : all sec...,201408,M,0.24761,thousand megawatthours
36,Net generation : all solar : Wyoming : all sec...,201407,M,0.25935,thousand megawatthours
37,Net generation : all solar : Wyoming : all sec...,201406,M,0.24267,thousand megawatthours
38,Net generation : all solar : Wyoming : all sec...,201405,M,0.24298,thousand megawatthours
39,Net generation : all solar : Wyoming : all sec...,201404,M,0.21795,thousand megawatthours
40,Net generation : all solar : Wyoming : all sec...,201403,M,0.18729,thousand megawatthours
41,Net generation : all solar : Wyoming : all sec...,201402,M,0.13289,thousand megawatthours
42,Net generation : all solar : Wyoming : all sec...,201401,M,0.11748,thousand megawatthours

In [7]:
result.to_csv('Electricity__Net_generation__By_fuel_type__All_Solar.csv',sep=',',encoding='utf-8')