In [1]:
import pandas as pd 
import requests
state_list=["https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.AL-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.AK-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.AZ-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.AR-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.CA-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.CO-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.CT-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.DE-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.DC-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.ENC-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.ESC-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.FL-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.GA-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.HI-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.ID-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.IL-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.IN-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.IA-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.KS-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.KY-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.LA-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.ME-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.MD-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.MA-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.MI-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.MAT-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.MN-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.MS-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.MO-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.MT-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.MTN-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.NE-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.NV-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.NEW-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.NH-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.NJ-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.NM-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.NY-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.NC-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.ND-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.OH-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.OK-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.OR-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.PCC-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.PCN-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.PA-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.RI-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.SAT-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.SC-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.SD-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.TN-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.TX-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.US-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.UT-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.VT-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.VA-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.WA-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.WNC-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.WSC-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.WV-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.WI-ALL.M",
"https://www.eia.gov/opendata/qb.php?category=39&sdid=ELEC.REV.WY-ALL.M"]
print("done")

done

In [2]:
raw={}
df={}
for i in range(0,len(state_list)):
    raw[i]=pd.read_html(state_list[i])
    df[i]=list(raw[i])
    df[i]=pd.DataFrame(df[i][0])
    print("done")
print("wow done amaze")

done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
wow done amaze

In [3]:
frames=[df[i] for i in range(0,len(state_list))]
result=pd.concat(frames)
print("done")

done

In [4]:
result

,Series Name,Period,Frequency,Value,Units
0,Revenue from retail sales of electricity : Ala...,201707,M,878.76993,million dollars
1,Revenue from retail sales of electricity : Ala...,201706,M,766.67053,million dollars
2,Revenue from retail sales of electricity : Ala...,201705,M,681.01506,million dollars
3,Revenue from retail sales of electricity : Ala...,201704,M,623.23465,million dollars
4,Revenue from retail sales of electricity : Ala...,201703,M,643.88836,million dollars
5,Revenue from retail sales of electricity : Ala...,201702,M,605.89544,million dollars
6,Revenue from retail sales of electricity : Ala...,201701,M,689.47008,million dollars
7,Revenue from retail sales of electricity : Ala...,201612,M,684.63402,million dollars
8,Revenue from retail sales of electricity : Ala...,201611,M,591.91583,million dollars
9,Revenue from retail sales of electricity : Ala...,201610,M,673.45096,million dollars
10,Revenue from retail sales of electricity : Ala...,201609,M,806.47934,million dollars
11,Revenue from retail sales of electricity : Ala...,201608,M,884.61376,million dollars
12,Revenue from retail sales of electricity : Ala...,201607,M,884.35216,million dollars
13,Revenue from retail sales of electricity : Ala...,201606,M,787.71612,million dollars
14,Revenue from retail sales of electricity : Ala...,201605,M,642.76974,million dollars
15,Revenue from retail sales of electricity : Ala...,201604,M,572.75007,million dollars
16,Revenue from retail sales of electricity : Ala...,201603,M,585.36658,million dollars
17,Revenue from retail sales of electricity : Ala...,201602,M,628.02937,million dollars
18,Revenue from retail sales of electricity : Ala...,201601,M,687.31715,million dollars
19,Revenue from retail sales of electricity : Ala...,201512,M,578.41295,million dollars
20,Revenue from retail sales of electricity : Ala...,201511,M,546.40601,million dollars
21,Revenue from retail sales of electricity : Ala...,201510,M,601.68413,million dollars
22,Revenue from retail sales of electricity : Ala...,201509,M,749.42108,million dollars
23,Revenue from retail sales of electricity : Ala...,201508,M,859.08913,million dollars
24,Revenue from retail sales of electricity : Ala...,201507,M,883.14036,million dollars
25,Revenue from retail sales of electricity : Ala...,201506,M,795.57473,million dollars
26,Revenue from retail sales of electricity : Ala...,201505,M,660.90864,million dollars
27,Revenue from retail sales of electricity : Ala...,201504,M,574.10881,million dollars
28,Revenue from retail sales of electricity : Ala...,201503,M,636.10890,million dollars
29,Revenue from retail sales of electricity : Ala...,201502,M,692.75712,million dollars
...,...,...,...,...,...
169,Revenue from retail sales of electricity : Wyo...,200306,M,51.12842,million dollars
170,Revenue from retail sales of electricity : Wyo...,200305,M,50.46875,million dollars
171,Revenue from retail sales of electricity : Wyo...,200304,M,51.02613,million dollars
172,Revenue from retail sales of electricity : Wyo...,200303,M,59.46663,million dollars
173,Revenue from retail sales of electricity : Wyo...,200302,M,52.99415,million dollars
174,Revenue from retail sales of electricity : Wyo...,200301,M,53.04045,million dollars
175,Revenue from retail sales of electricity : Wyo...,200212,M,52.40519,million dollars
176,Revenue from retail sales of electricity : Wyo...,200211,M,50.86096,million dollars
177,Revenue from retail sales of electricity : Wyo...,200210,M,51.22276,million dollars
178,Revenue from retail sales of electricity : Wyo...,200209,M,48.93715,million dollars
179,Revenue from retail sales of electricity : Wyo...,200208,M,50.89428,million dollars
180,Revenue from retail sales of electricity : Wyo...,200207,M,50.82436,million dollars
181,Revenue from retail sales of electricity : Wyo...,200206,M,47.96483,million dollars
182,Revenue from retail sales of electricity : Wyo...,200205,M,48.16448,million dollars
183,Revenue from retail sales of electricity : Wyo...,200204,M,48.39638,million dollars
184,Revenue from retail sales of electricity : Wyo...,200203,M,51.09133,million dollars
185,Revenue from retail sales of electricity : Wyo...,200202,M,48.57781,million dollars
186,Revenue from retail sales of electricity : Wyo...,200201,M,52.98447,million dollars
187,Revenue from retail sales of electricity : Wyo...,200112,M,51.15652,million dollars
188,Revenue from retail sales of electricity : Wyo...,200111,M,49.30379,million dollars
189,Revenue from retail sales of electricity : Wyo...,200110,M,48.02515,million dollars
190,Revenue from retail sales of electricity : Wyo...,200109,M,48.02965,million dollars
191,Revenue from retail sales of electricity : Wyo...,200108,M,52.45932,million dollars
192,Revenue from retail sales of electricity : Wyo...,200107,M,47.68529,million dollars
193,Revenue from retail sales of electricity : Wyo...,200106,M,45.39365,million dollars
194,Revenue from retail sales of electricity : Wyo...,200105,M,44.83900,million dollars
195,Revenue from retail sales of electricity : Wyo...,200104,M,45.10077,million dollars
196,Revenue from retail sales of electricity : Wyo...,200103,M,47.80066,million dollars
197,Revenue from retail sales of electricity : Wyo...,200102,M,49.14779,million dollars
198,Revenue from retail sales of electricity : Wyo...,200101,M,48.12840,million dollars

In [5]:
result.to_csv('Electricity__Revenue_from_retail_sales_of_electricity.csv',sep=',',encoding='utf-8')