In [6]:
# before you run this on your device , install packages requests, Beautifulsoup , pretty print , pandas , numpy
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

# to run it for any other cryptocurrency , mess around with the currency name ( this one says bitcoin)
# to mess around with the date range , change the inputs for the start and end date 
# the best part about this is the date ranges are not really constricting us ... ( cont )
# bitcoin data exists from 2013 apr 28 , but even if you give the input as 2012 whatever , it still returns only the data we need
# so there's that 
page = requests.get("https://coinmarketcap.com/currencies/bitcoin/historical-data/?start=20130428&end=20170919")
# A 200 response means that the request was executed
page

In [7]:
soup = BeautifulSoup(page.content, 'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
 <!--<![endif]-->
 <head>
  <title>
   Bitcoin (BTC) Historical Data | CoinMarketCap
  </title>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="EDc1reqlQ-zAgeRrrgAxRXNK-Zs9JgpE9a0wdaoSO9A" name="google-site-verification"/>
  <meta content="website" property="og:type"/>
  <meta content="image/png" property="og:image:type"/>
  <meta content="200" property="og:image:width"/>
  <meta content="200" property="og:image:height"/>
  <meta content="http://files.coinmarketcap.com.s3-website-us-east-1.amazonaws.com/static/img/coins/200x200/bitcoin.png" property="og:image"/>
  <meta content="Bitcoin (BTC) historical data | CoinMarketCap" property="og:title"/>
  <meta content="View Bitcoin daily historical data (OHLCV)" name="description"/>
  <meta content="View Bitcoin daily historical data (OHLCV)" property="og:description"/>
  <link href="https://files.coinmarketcap.com/static/img/coins/16x16/bitcoin.png" rel="shortcut icon" type="image/png"/>
  <link href="https://coinmarketcap.com/currencies/bitcoin/historical-data/?start=20130428&amp;end=20170919" rel="canonical"/>
  <script>
   function getCookie(e){var n=" "+document.cookie,t=" "+e+"=",i=null,o=0,u=0;return n.length>0&&-1!=(o=n.indexOf(t))&&(o+=t.length,-1==(u=n.indexOf(";",o))&&(u=n.length),i=unescape(n.substring(o,u))),i}

        dataLayer = [{
            'section': 'Details',
            'subSection': 'Currencies Historical Data',
            'firstSessionDate': getCookie('gtm_session_first'),
            'lastSessionDate': getCookie('gtm_session_last'),
            'language': 'en-us',
        }];
  </script>
  <!-- Google Tag Manager -->
  <script>
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-MNVXW26');
  </script>
  <!-- End Google Tag Manager -->
  <link href="/static/compressed/base.min.css?ef348a90" rel="stylesheet" type="text/css"/>
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css"/>
  <link href="/static/img/CoinMarketCap.png" rel="apple-touch-icon"/>
  <link href="/static/.bower_components/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet"/>
  <script async="async" src="/static/compressed/prebid.min.js?76ac70a3">
  </script>
  <script async="async" src="https://www.googletagservices.com/tag/js/gpt.js">
  </script>
  <script>
   var googletag = googletag || {};
            googletag.cmd = googletag.cmd || [];
            googletag.cmd.push(function() {
                googletag.pubads().disableInitialLoad();
            });
  </script>
  <script type="text/javascript">
   googletag.cmd.push(function() {


                    googletag.defineSlot('/48901027/non_landing_leaderboard_top', [728, 90], 'div-gpt-ad-1488495260324-9').addService(googletag.pubads());
                    googletag.defineSlot('/48901027/non_landing_side', [160, 600], 'div-gpt-ad-1488495260324-10').addService(googletag.pubads());
                    googletag.defineSlot('/48901027/non_landing_leaderboard_bottom', [728, 90], 'div-gpt-ad-1488495260324-8').addService(googletag.pubads());




                googletag.pubads().setTargeting("coin_id","1");


            googletag.pubads().enableSingleRequest();
            googletag.enableServices();
          });
  </script>
  <script>
   //Load the UAM JavaScript Library
        !function(a9,a,p,s,t,A,g){if(a[a9])return;function
        q(c,r){a[a9]._Q.push([c,r])}a[a9]={init:function(){q("i",arguments)},fetchBids:function(){q("f",arguments)},setDisplayBids:function(){},targetingKeys:function(){return[]},_Q:[]};A=p.createElement(s);A.async=!0;A.src=t;g=p.getElementsByTagName(s)[0];g.parentNode.insertBefore(A,g)}("apstag",window,document,"script","//c.amazon-adsystem.com/aax2/apstag.js");
        apstag.init({
            pubID: '3574',
            adServer: 'googletag',
            bidTimeout: 2000
        });

        var pbjs = pbjs || {};
        pbjs.que = pbjs.que || [];
  </script>
  <script>
   function fetchHeaderBids() {
            var bidTimeout = 2000;
            var adUnits = [


                    {
                        code: 'div-gpt-ad-1488495260324-9',
                        sizes: [[728, 90]],
                        bids: [
                        {
                            "bidder": "appnexus",
                            "params": {
                                "placementId": "11835084" // [D] 728x90 Detail ATF: 11835084
                            }
                        }]
                    },{
                        code: 'div-gpt-ad-1488495260324-10',
                        sizes: [[160, 600]],
                        bids: [
                        {
                            "bidder": "openx",
                            "params": {
                                "unit": "539181152",
                                "delDomain": "coinmarketcap-d.openx.net" // Desktop - 160x600 Detail page
                            }
                        },
                        {
                            "bidder": "appnexus",
                            "params": {
                                "placementId": "11835085" // [D] 160x600 Detail: 11835085
                            }
                        },
                        {
                            "bidder": "komoona",
                            "params": {
                                "hbid": "868287e9bf904b8998fbf3d45d55d3af",
                                "placementId": "0c749a3c08941c23619df0ff76b1369a" // Coinmarketcap.com Detail page 160x600
                            }
                        },
                        {
                            "bidder": "sovrn",
                            "params": {
                                "tagid": "496633" // CoinMarketCap_AiH_160x600_Side_DETAILPAGE_Desktop
                            }
                        }]
                    },{
                        code: 'div-gpt-ad-1488495260324-8',
                        sizes: [[728, 90]],
                        bids: [
                        {
                            "bidder": "openx",
                            "params": {
                                "unit": "539181150",
                                "delDomain": "coinmarketcap-d.openx.net" // Desktop - 728x90 BTF Detail page
                            }
                        },
                        {
                            "bidder": "appnexus",
                            "params": {
                                "placementId": "11835086" // [D] 728x90 Detail BTF: 11835086
                            }
                        },
                        {
                            "bidder": "komoona",
                            "params": {
                                "hbid": "868287e9bf904b8998fbf3d45d55d3af",
                                "placementId": "386e40457d4a1238421745637817317d" // Coinmarketcap.com BTF Detail page 728x90
                            }
                        },
                        {
                            "bidder": "sovrn",
                            "params": {
                                "tagid": "496631" // CoinMarketCap_AiH_728x90_BTF_DETAILPAGE_Desktop
                            }
                        }]
                    }


            ];

            var apstagSlots = [


                    {
                        slotID: 'div-gpt-ad-1488495260324-9',
                        slotName: '/48901027/non_landing_leaderboard_top',
                        sizes: [[728, 90]]
                    },
                    {
                        slotID: 'div-gpt-ad-1488495260324-10',
                        slotName: '/48901027/non_landing_side',
                        sizes: [[160, 600]]
                    },
                    {
                        slotID: 'div-gpt-ad-1488495260324-8',
                        slotName: '/48901027/non_landing_leaderboard_bottom',
                        sizes: [[728, 90]]
                    }


            ];

            var bidders = ['a9', 'prebid'];

            var requestManager = {
                adserverRequestSent: false,
            };

                bidders.forEach(function(bidder) {
                requestManager[bidder] = false;
            })

            function allBiddersBack() {
                var allBiddersBack = bidders
                .map(function(bidder) {
                    return requestManager[bidder];
                })
                .filter(Boolean)
                .length === bidders.length;
                return allBiddersBack;
            }

            function headerBidderBack(bidder) {
                if (requestManager.adserverRequestSent === true) {
                    return;
                }
                if (bidder === 'a9') {
                    requestManager.a9 = true;
                } else if (bidder === 'prebid') {
                    requestManager.prebid = true;
                }
                if (allBiddersBack()) {
                    sendAdserverRequest();
                }
            }

            function sendAdserverRequest() {
                if (requestManager.adserverRequestSent === true) {
                    return;
                }

                if (!allBiddersBack()) {
                    var eventLabel = ''
                    eventLabel += requestManager.a9 ? "" : "a9"
                    eventLabel += requestManager.prebid ? "" : "prebid"
                    dataLayer.push({
                        'event': 'customEvent',
                        'eventCategory': 'Prebid',
                        'eventAction': 'Timeout',
                        'eventLabel': eventLabel,
                    });
                }
                requestManager.adserverRequestSent = true;
                pbjs.adserverRequestSent = true;
                requestManager.sendAdserverRequest = true;
                googletag.cmd.push(function() {
                    apstag.setDisplayBids();
                    pbjs.setTargetingForGPTAsync();
                    googletag.pubads().refresh();
                });
            }

            function requestBids(apstagSlots, adUnits, bidTimeout) {
                apstag.fetchBids({
                    slots: apstagSlots,
                    timeout: bidTimeout
                    }, function(bids) {
                        headerBidderBack('a9');
                    });

                // request bids from prebid
                pbjs.que.push(function() {
                    pbjs.setPriceGranularity("high");
                    pbjs.addAdUnits(adUnits);
                    pbjs.enableSendAllBids();
                    pbjs.bidderSettings = {
                      appnexus: {
                        bidCpmAdjustment : function(bidCpm){
                          return bidCpm * 0.66;
                        }
                      }
                    };

                    pbjs.requestBids({
                        bidsBackHandler: function (bids) {
                            headerBidderBack('prebid');
                        }
                    });
                });
            }

            requestBids(apstagSlots, adUnits, bidTimeout)
            window.setTimeout(function() {
                sendAdserverRequest();
            }, bidTimeout);
        };

        fetchHeaderBids();
  </script>
  <style>
   .icobanner-close {
            color:#FFF;
        }
        #icobanner-wrapper {
            text-align:center;
            background-color:#333;
        }
  </style>
 </head>
 <body>
  <!-- Google Tag Manager -->
  <noscript>
   <iframe height="0" src="//www.googletagmanager.com/ns.html?id=GTM-MNVXW26" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager -->
  <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
  <div id="icobanner-wrapper" style="display:none">
   <a href="https://worldcore.com/" rel="nofollow" target="_blank">
    <img alt="worldcore" class="icobanner-img" src="/static/sponsored/worldcore/worldcore_970x90.gif"/>
   </a>
   <div class="icobanner-close">
    X
   </div>
  </div>
  <div id="top-nav-outer-container" role="navigation">
   <div class="row">
    <div class="container" id="top-nav-inner-container">
     <div class="hidden-xs col-sm-3">
      <div class="small" id="global-stats-counts">
      </div>
     </div>
     <div class="col-xs-12 col-sm-7">
      <div class="small" id="global-stats-values">
      </div>
     </div>
     <div class="hidden-xs col-sm-2 text-right">
      <div class="pull-right" id="twitter-follow">
       <a class="twitter-follow-button" data-show-count="false" href="https://twitter.com/CoinMKTCap">
        Follow @CoinMKTCap
       </a>
       <script>
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
       </script>
      </div>
     </div>
    </div>
   </div>
  </div>
  <div class="container">
   <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-10">
     <div id="title">
      <a href="/">
       Cryptocurrency Market Capitalizations
      </a>
     </div>
     <hr/>
     <div class="text-center" id="leaderboard">
      <!-- /48901027/non_landing_leaderboard_top -->
      <div class="centered leaderboard" id="div-gpt-ad-1488495260324-9">
       <script>
        googletag.cmd.push(function() { googletag.display('div-gpt-ad-1488495260324-9'); });
       </script>
      </div>
     </div>
     <nav class="navbar navbar-default" id="nav-main">
      <div class="navbar-header">
       <button class="navbar-toggle" data-target="#navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">
         Toggle navigation
        </span>
        <span class="icon-bar">
        </span>
        <span class="icon-bar">
        </span>
        <span class="icon-bar">
        </span>
       </button>
      </div>
      <div class="collapse navbar-collapse" id="navbar-collapse-1">
       <ul class="nav navbar-nav">
        <li class="dropdown">
         <a class="dropdown-toggle" data-toggle="dropdown" href="/">
          Market Cap
          <span class="caret">
          </span>
         </a>
         <ul class="dropdown-menu" role="menu">
          <li>
           <a href="/">
            All
           </a>
          </li>
          <li>
           <a href="/coins/">
            Coins
           </a>
          </li>
          <li>
           <a href="/tokens/">
            Tokens
           </a>
          </li>
         </ul>
        </li>
        <li class="dropdown">
         <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          Trade Volume
          <span class="caret">
          </span>
         </a>
         <ul class="dropdown-menu" role="menu">
          <li>
           <a href="/currencies/volume/24-hour/">
            24 Hour Volume Rankings (Currency)
           </a>
          </li>
          <li>
           <a href="/exchanges/volume/24-hour/">
            24 Hour Volume Rankings (Exchange)
           </a>
          </li>
          <li>
           <a href="/currencies/volume/monthly/">
            Monthly Volume Rankings (Currency)
           </a>
          </li>
         </ul>
        </li>
        <li class="dropdown">
         <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          Trending
          <span class="caret">
          </span>
         </a>
         <ul class="dropdown-menu" role="menu">
          <li>
           <a href="/gainers-losers/">
            Gainers and Losers
           </a>
          </li>
          <li>
           <a href="/new/">
            Recently Added
           </a>
          </li>
         </ul>
        </li>
        <li class="dropdown">
         <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          Tools
          <span class="caret">
          </span>
         </a>
         <ul class="dropdown-menu" role="menu">
          <li>
           <a href="/charts/">
            Global Charts
           </a>
          </li>
          <li>
           <a href="/historical/">
            Historical Snapshots
           </a>
          </li>
          <li>
           <a href="/calculator/">
            Currency Converter Calculator
           </a>
          </li>
          <li>
           <a href="/widget/">
            Website Widgets
           </a>
          </li>
         </ul>
        </li>
       </ul>
       <form action="/currencies/search/" class="navbar-form navbar-right" role="search">
        <div class="form-group">
         <input class="form-control js-quick-search" id="quick-search-box" name="q" placeholder="Search Currencies" type="text"/>
         <button class="btn btn-primary hidden-sm hidden-md hidden-lg" type="submit">
          <i class="glyphicon glyphicon-search">
          </i>
         </button>
        </div>
        <button class="btn btn-primary hidden-xs" type="submit">
         <i class="glyphicon glyphicon-search">
         </i>
        </button>
       </form>
       <div class="bottom-margin-1x hidden-sm hidden-md hidden-lg">
       </div>
      </div>
     </nav>
     <div class="row bottom-margin-1x">
      <div class="col-xs-6 col-sm-4 col-md-4">
       <h1 class="text-large">
        <img alt="Bitcoin" class="currency-logo-32x32" src="https://files.coinmarketcap.com/static/img/coins/32x32/bitcoin.png"/>
        <small class="bold hidden-sm hidden-md hidden-lg">
         (BTC)
        </small>
        Bitcoin
        <small class="bold hidden-xs">
         (BTC)
        </small>
       </h1>
      </div>
      <div class="col-xs-6 col-sm-8 col-md-4 text-left">
       <span class="text-large" id="quote_price">
        $5521.38
       </span>
       <span class="text-large negative_change">
        (-3.52%)
       </span>
       <br/>
       <small class="text-gray">
        1.00 BTC
       </small>
       <small class=" positive_change ">
        (0.00%)
       </small>
       <div class="row">
        <div class="col-xs-12 col-sm-12 hidden-md hidden-lg text-left">
         <!-- Mobile Button -->
         <a href="https://changelly.com/exchange/USD/BTC/50?ref_id=coinmarketcap" rel="nofollow" target="_blank">
          <div class="btn btn-primary btn-xs">
           <span class="glyphicon glyphicon-flash">
           </span>
           Buy / Sell Instantly
          </div>
         </a>
        </div>
       </div>
      </div>
      <div class="hidden-xs hidden-sm col-md-4 text-left">
       <a href=" https://changelly.com/exchange/USD/BTC/50?ref_id=coinmarketcap" rel="nofollow" target="_blank">
        <div class="btn btn-primary">
         <span class="glyphicon glyphicon-flash">
         </span>
         Buy instantly with credit card
        </div>
       </a>
      </div>
     </div>
     <div class="row bottom-margin-2x">
      <div class="col-sm-8 col-sm-push-4">

In [5]:
list(soup.children)

['html',
 '\n',
 '[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]',
 '\n',
 '[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]',
 '\n',
 '[if IE 8]>         <html class="no-js lt-ie9"> <![endif]',
 '\n',
 '[if gt IE 8]><!',
 '\n',
 <html class="no-js"> <!--<![endif]-->
 <head>
 <title>Bitcoin (BTC) Historical Data | CoinMarketCap</title>
 <meta charset="utf-8"/>
 <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
 <meta content="EDc1reqlQ-zAgeRrrgAxRXNK-Zs9JgpE9a0wdaoSO9A" name="google-site-verification"/>
 <meta content="website" property="og:type"/>
 <meta content="image/png" property="og:image:type"/>
 <meta content="200" property="og:image:width"/>
 <meta content="200" property="og:image:height"/>
 <meta content="http://files.coinmarketcap.com.s3-website-us-east-1.amazonaws.com/static/img/coins/200x200/bitcoin.png" property="og:image"/>
 <meta content="Bitcoin (BTC) historical data | CoinMarketCap" property="og:title"/>
 <meta content="View Bitcoin daily historical data (OHLCV)" name="description"/>
 <meta content="View Bitcoin daily historical data (OHLCV)" property="og:description"/>
 <link href="https://files.coinmarketcap.com/static/img/coins/16x16/bitcoin.png" rel="shortcut icon" type="image/png"/>
 <link href="https://coinmarketcap.com/currencies/bitcoin/historical-data/?start=20130428&amp;end=20170919" rel="canonical"/>
 <script>
         function getCookie(e){var n=" "+document.cookie,t=" "+e+"=",i=null,o=0,u=0;return n.length>0&&-1!=(o=n.indexOf(t))&&(o+=t.length,-1==(u=n.indexOf(";",o))&&(u=n.length),i=unescape(n.substring(o,u))),i}

         dataLayer = [{
             'section': 'Details',
             'subSection': 'Currencies Historical Data',
             'firstSessionDate': getCookie('gtm_session_first'),
             'lastSessionDate': getCookie('gtm_session_last'),
             'language': 'en-us',
         }];
         </script>
 <!-- Google Tag Manager -->
 <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-MNVXW26');
         </script>
 <!-- End Google Tag Manager -->
 <link href="/static/compressed/base.min.css?ef348a90" rel="stylesheet" type="text/css"/>
 <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css"/>
 <link href="/static/img/CoinMarketCap.png" rel="apple-touch-icon"/>
 <link href="/static/.bower_components/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet"/>
 <script async="async" src="/static/compressed/prebid.min.js?76ac70a3"></script>
 <script async="async" src="https://www.googletagservices.com/tag/js/gpt.js"></script>
 <script>
             var googletag = googletag || {};
             googletag.cmd = googletag.cmd || [];
             googletag.cmd.push(function() {
                 googletag.pubads().disableInitialLoad();
             });
         </script>
 <script type="text/javascript">
           googletag.cmd.push(function() {


                     googletag.defineSlot('/48901027/non_landing_leaderboard_top', [728, 90], 'div-gpt-ad-1488495260324-9').addService(googletag.pubads());
                     googletag.defineSlot('/48901027/non_landing_side', [160, 600], 'div-gpt-ad-1488495260324-10').addService(googletag.pubads());
                     googletag.defineSlot('/48901027/non_landing_leaderboard_bottom', [728, 90], 'div-gpt-ad-1488495260324-8').addService(googletag.pubads());




                 googletag.pubads().setTargeting("coin_id","1");


             googletag.pubads().enableSingleRequest();
             googletag.enableServices();
           });
         </script>
 <script>

         //Load the UAM JavaScript Library
         !function(a9,a,p,s,t,A,g){if(a[a9])return;function
         q(c,r){a[a9]._Q.push([c,r])}a[a9]={init:function(){q("i",arguments)},fetchBids:function(){q("f",arguments)},setDisplayBids:function(){},targetingKeys:function(){return[]},_Q:[]};A=p.createElement(s);A.async=!0;A.src=t;g=p.getElementsByTagName(s)[0];g.parentNode.insertBefore(A,g)}("apstag",window,document,"script","//c.amazon-adsystem.com/aax2/apstag.js");
         apstag.init({
             pubID: '3574',
             adServer: 'googletag',
             bidTimeout: 2000
         });

         var pbjs = pbjs || {};
         pbjs.que = pbjs.que || [];

         </script>
 <script>
         function fetchHeaderBids() {
             var bidTimeout = 2000;
             var adUnits = [


                     {
                         code: 'div-gpt-ad-1488495260324-9',
                         sizes: [[728, 90]],
                         bids: [
                         {
                             "bidder": "appnexus",
                             "params": {
                                 "placementId": "11835084" // [D] 728x90 Detail ATF: 11835084
                             }
                         }]
                     },{
                         code: 'div-gpt-ad-1488495260324-10',
                         sizes: [[160, 600]],
                         bids: [
                         {
                             "bidder": "openx",
                             "params": {
                                 "unit": "539181152",
                                 "delDomain": "coinmarketcap-d.openx.net" // Desktop - 160x600 Detail page
                             }
                         },
                         {
                             "bidder": "appnexus",
                             "params": {
                                 "placementId": "11835085" // [D] 160x600 Detail: 11835085
                             }
                         },
                         {
                             "bidder": "komoona",
                             "params": {
                                 "hbid": "868287e9bf904b8998fbf3d45d55d3af",
                                 "placementId": "0c749a3c08941c23619df0ff76b1369a" // Coinmarketcap.com Detail page 160x600
                             }
                         },
                         {
                             "bidder": "sovrn",
                             "params": {
                                 "tagid": "496633" // CoinMarketCap_AiH_160x600_Side_DETAILPAGE_Desktop
                             }
                         }]
                     },{
                         code: 'div-gpt-ad-1488495260324-8',
                         sizes: [[728, 90]],
                         bids: [
                         {
                             "bidder": "openx",
                             "params": {
                                 "unit": "539181150",
                                 "delDomain": "coinmarketcap-d.openx.net" // Desktop - 728x90 BTF Detail page
                             }
                         },
                         {
                             "bidder": "appnexus",
                             "params": {
                                 "placementId": "11835086" // [D] 728x90 Detail BTF: 11835086
                             }
                         },
                         {
                             "bidder": "komoona",
                             "params": {
                                 "hbid": "868287e9bf904b8998fbf3d45d55d3af",
                                 "placementId": "386e40457d4a1238421745637817317d" // Coinmarketcap.com BTF Detail page 728x90
                             }
                         },
                         {
                             "bidder": "sovrn",
                             "params": {
                                 "tagid": "496631" // CoinMarketCap_AiH_728x90_BTF_DETAILPAGE_Desktop
                             }
                         }]
                     }


             ];

             var apstagSlots = [


                     {
                         slotID: 'div-gpt-ad-1488495260324-9',
                         slotName: '/48901027/non_landing_leaderboard_top',
                         sizes: [[728, 90]]
                     },
                     {
                         slotID: 'div-gpt-ad-1488495260324-10',
                         slotName: '/48901027/non_landing_side',
                         sizes: [[160, 600]]
                     },
                     {
                         slotID: 'div-gpt-ad-1488495260324-8',
                         slotName: '/48901027/non_landing_leaderboard_bottom',
                         sizes: [[728, 90]]
                     }


             ];

             var bidders = ['a9', 'prebid'];

             var requestManager = {
                 adserverRequestSent: false,
             };

                 bidders.forEach(function(bidder) {
                 requestManager[bidder] = false;
             })

             function allBiddersBack() {
                 var allBiddersBack = bidders
                 .map(function(bidder) {
                     return requestManager[bidder];
                 })
                 .filter(Boolean)
                 .length === bidders.length;
                 return allBiddersBack;
             }

             function headerBidderBack(bidder) {
                 if (requestManager.adserverRequestSent === true) {
                     return;
                 }
                 if (bidder === 'a9') {
                     requestManager.a9 = true;
                 } else if (bidder === 'prebid') {
                     requestManager.prebid = true;
                 }
                 if (allBiddersBack()) {
                     sendAdserverRequest();
                 }
             }

             function sendAdserverRequest() {
                 if (requestManager.adserverRequestSent === true) {
                     return;
                 }

                 if (!allBiddersBack()) {
                     var eventLabel = ''
                     eventLabel += requestManager.a9 ? "" : "a9"
                     eventLabel += requestManager.prebid ? "" : "prebid"
                     dataLayer.push({
                         'event': 'customEvent',
                         'eventCategory': 'Prebid',
                         'eventAction': 'Timeout',
                         'eventLabel': eventLabel,
                     });
                 }
                 requestManager.adserverRequestSent = true;
                 pbjs.adserverRequestSent = true;
                 requestManager.sendAdserverRequest = true;
                 googletag.cmd.push(function() {
                     apstag.setDisplayBids();
                     pbjs.setTargetingForGPTAsync();
                     googletag.pubads().refresh();
                 });
             }

             function requestBids(apstagSlots, adUnits, bidTimeout) {
                 apstag.fetchBids({
                     slots: apstagSlots,
                     timeout: bidTimeout
                     }, function(bids) {
                         headerBidderBack('a9');
                     });

                 // request bids from prebid
                 pbjs.que.push(function() {
                     pbjs.setPriceGranularity("high");
                     pbjs.addAdUnits(adUnits);
                     pbjs.enableSendAllBids();
                     pbjs.bidderSettings = {
                       appnexus: {
                         bidCpmAdjustment : function(bidCpm){
                           return bidCpm * 0.66;
                         }
                       }
                     };

                     pbjs.requestBids({
                         bidsBackHandler: function (bids) {
                             headerBidderBack('prebid');
                         }
                     });
                 });
             }

             requestBids(apstagSlots, adUnits, bidTimeout)
             window.setTimeout(function() {
                 sendAdserverRequest();
             }, bidTimeout);
         };

         fetchHeaderBids();

         </script>
 <style>
         .icobanner-close {
             color:#FFF;
         }
         #icobanner-wrapper {
             text-align:center;
             background-color:#333;
         }
     </style>
 </head>
 <body>
 <!-- Google Tag Manager -->
 <noscript><iframe height="0" src="//www.googletagmanager.com/ns.html?id=GTM-MNVXW26" style="display:none;visibility:hidden" width="0"></iframe></noscript>
 <!-- End Google Tag Manager -->
 <!--[if lt IE 7]>
             <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
         <![endif]-->
 <div id="icobanner-wrapper" style="display:none">
 <a href="https://worldcore.com/" rel="nofollow" target="_blank"><img alt="worldcore" class="icobanner-img" src="/static/sponsored/worldcore/worldcore_970x90.gif"/></a>
 <div class="icobanner-close">X</div>
 </div>
 <div id="top-nav-outer-container" role="navigation">
 <div class="row">
 <div class="container" id="top-nav-inner-container">
 <div class="hidden-xs col-sm-3">
 <div class="small" id="global-stats-counts"></div>
 </div>
 <div class="col-xs-12 col-sm-7">
 <div class="small" id="global-stats-values"></div>
 </div>
 <div class="hidden-xs col-sm-2 text-right">
 <div class="pull-right" id="twitter-follow">
 <a class="twitter-follow-button" data-show-count="false" href="https://twitter.com/CoinMKTCap">Follow @CoinMKTCap</a>
 <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
 </div>
 </div>
 </div>
 </div>
 </div>
 <div class="container">
 <div class="row">
 <div class="col-xs-12 col-sm-12 col-md-12 col-lg-10">
 <div id="title"><a href="/">Cryptocurrency Market Capitalizations</a></div>
 <hr/>
 <div class="text-center" id="leaderboard">
 <!-- /48901027/non_landing_leaderboard_top -->
 <div class="centered leaderboard" id="div-gpt-ad-1488495260324-9">
 <script>
                                     googletag.cmd.push(function() { googletag.display('div-gpt-ad-1488495260324-9'); });
                                     </script>
 </div>
 </div>
 <nav class="navbar navbar-default" id="nav-main">
 <div class="navbar-header">
 <button class="navbar-toggle" data-target="#navbar-collapse-1" data-toggle="collapse" type="button">
 <span class="sr-only">Toggle navigation</span>
 <span class="icon-bar"></span>
 <span class="icon-bar"></span>
 <span class="icon-bar"></span>
 </button>
 </div>
 <div class="collapse navbar-collapse" id="navbar-collapse-1">
 <ul class="nav navbar-nav">
 <li class="dropdown">
 <a class="dropdown-toggle" data-toggle="dropdown" href="/">Market Cap <span class="caret"></span></a>
 <ul class="dropdown-menu" role="menu">
 <li><a href="/">All</a></li>
 <li><a href="/coins/">Coins</a></li>
 <li><a href="/tokens/">Tokens</a></li>
 </ul>
 </li>
 <li class="dropdown">
 <a class="dropdown-toggle" data-toggle="dropdown" href="#">Trade Volume <span class="caret"></span></a>
 <ul class="dropdown-menu" role="menu">
 <li><a href="/currencies/volume/24-hour/">24 Hour Volume Rankings (Currency)</a></li>
 <li><a href="/exchanges/volume/24-hour/">24 Hour Volume Rankings (Exchange)</a></li>
 <li><a href="/currencies/volume/monthly/">Monthly Volume Rankings (Currency)</a></li>
 </ul>
 </li>
 <li class="dropdown">
 <a class="dropdown-toggle" data-toggle="dropdown" href="#">Trending <span class="caret"></span></a>
 <ul class="dropdown-menu" role="menu">
 <li><a href="/gainers-losers/">Gainers and Losers</a></li>
 <li><a href="/new/">Recently Added</a></li>
 </ul>
 </li>
 <li class="dropdown">
 <a class="dropdown-toggle" data-toggle="dropdown" href="#">Tools <span class="caret"></span></a>
 <ul class="dropdown-menu" role="menu">
 <li><a href="/charts/">Global Charts</a></li>
 <li><a href="/historical/">Historical Snapshots</a></li>
 <li><a href="/calculator/">Currency Converter Calculator</a></li>
 <li><a href="/widget/">Website Widgets</a></li>
 </ul>
 </li>
 </ul>
 <form action="/currencies/search/" class="navbar-form navbar-right" role="search">
 <div class="form-group">
 <input class="form-control js-quick-search" id="quick-search-box" name="q" placeholder="Search Currencies" type="text"/>
 <button class="btn btn-primary hidden-sm hidden-md hidden-lg" type="submit"><i class="glyphicon glyphicon-search"></i></button>
 </div>
 <button class="btn btn-primary hidden-xs" type="submit"><i class="glyphicon glyphicon-search"></i></button>
 </form>
 <div class="bottom-margin-1x hidden-sm hidden-md hidden-lg"></div>
 </div>
 </nav>
 <div class="row bottom-margin-1x">
 <div class="col-xs-6 col-sm-4 col-md-4">
 <h1 class="text-large">
 <img alt="Bitcoin" class="currency-logo-32x32" src="https://files.coinmarketcap.com/static/img/coins/32x32/bitcoin.png"/>
 <small class="bold hidden-sm hidden-md hidden-lg">(BTC)</small>
                 Bitcoin
                 <small class="bold hidden-xs">(BTC)</small>
 </h1>
 </div>
 <div class="col-xs-6 col-sm-8 col-md-4 text-left">
 <span class="text-large" id="quote_price">$5521.38</span> <span class="text-large negative_change">(-3.52%)</span>
 <br/>
 <small class="text-gray">1.00 BTC</small> <small class=" positive_change "> (0.00%)</small>
 <div class="row">
 <div class="col-xs-12 col-sm-12 hidden-md hidden-lg text-left">
 <!-- Mobile Button -->
 <a href="https://changelly.com/exchange/USD/BTC/50?ref_id=coinmarketcap" rel="nofollow" target="_blank">
 <div class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-flash"></span> Buy / Sell Instantly</div>
 </a>
 </div>
 </div>
 </div>
 <div class="hidden-xs hidden-sm col-md-4 text-left">
 <a href=" https://changelly.com/exchange/USD/BTC/50?ref_id=coinmarketcap" rel="nofollow" target="_blank">
 <div class="btn btn-primary"><span class="glyphicon glyphicon-flash"></span>
                          Buy instantly with credit card
                     </div>
 </a>
 </div>
 </div>
 <div class="row bottom-margin-2x">
 <div class="col-sm-8 col-sm-push-4">
 <div class="coin-summary-item col-xs-6 col-md-3">
 <div class="coin-summary-item-header">
 <h3>Market Cap</h3>
 </div>
 <div class="coin-summary-item-detail">
                       $91,793,146,791 <br/>
 <span class="text-gray">16,625,037 BTC</span> <br/>
 </div>
 </div>
 <div class="coin-summary-item col-xs-6 col-md-3">
 <div class="coin-summary-item-header">
 <h3>Volume (24h)</h3>
 </div>
 <div class="coin-summary-item-detail">
                       $1,857,980,000<br/>
 <span class="text-gray">337,549 BTC</span>
 </div>
 </div>
 <div class="vertical-spacer col-xs-12 hidden-md hidden-lg"></div>
 <div class="coin-summary-item col-xs-6 col-md-3">
 <div class="coin-summary-item-header">
 <h3>Circulating Supply</h3>
 </div>
 <div class="coin-summary-item-detail">
                       16,625,037 BTC
                     </div>
 </div>
 <div class="coin-summary-item col-xs-6 col-md-3 ">
 <div class="coin-summary-item-header">
 <h3>Max Supply</h3>
 </div>
 <div class="coin-summary-item-detail">
                     21,000,000 BTC
                   </div>
 </div>
 <div class="clearfix visible-xs"></div>
 </div>
 <div class="col-sm-4 col-sm-pull-8">
 <ul class="list-unstyled">
 <li><span class="glyphicon glyphicon-link text-gray" title="Website"></span> <a href="https://bitcoin.org/" target="_blank">Website</a></li>
 <li><span class="glyphicon glyphicon-link text-gray" title="Website"></span> <a href="https://www.bitcoin.com/" target="_blank">Website 2</a></li>

[bs4.element.Doctype,
 bs4.element.NavigableString,
 bs4.element.Comment,
 bs4.element.NavigableString,
 bs4.element.Comment,
 bs4.element.NavigableString,
 bs4.element.Comment,
 bs4.element.NavigableString,
 bs4.element.Comment,
 bs4.element.NavigableString,
 bs4.element.Tag]

<html class="no-js"> <!--<![endif]-->
<head>
<title>Bitcoin (BTC) Historical Data | CoinMarketCap</title>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="EDc1reqlQ-zAgeRrrgAxRXNK-Zs9JgpE9a0wdaoSO9A" name="google-site-verification"/>
<meta content="website" property="og:type"/>
<meta content="image/png" property="og:image:type"/>
<meta content="200" property="og:image:width"/>
<meta content="200" property="og:image:height"/>
<meta content="http://files.coinmarketcap.com.s3-website-us-east-1.amazonaws.com/static/img/coins/200x200/bitcoin.png" property="og:image"/>
<meta content="Bitcoin (BTC) historical data | CoinMarketCap" property="og:title"/>
<meta content="View Bitcoin daily historical data (OHLCV)" name="description"/>
<meta content="View Bitcoin daily historical data (OHLCV)" property="og:description"/>
<link href="https://files.coinmarketcap.com/static/img/coins/16x16/bitcoin.png" rel="shortcut icon" type="image/png"/>
<link href="https://coinmarketcap.com/currencies/bitcoin/historical-data/?start=20130428&amp;end=20170919" rel="canonical"/>
<link href="/static/compressed/base.min.css?a9a98fb1" rel="stylesheet" type="text/css"/>
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css"/>
<link href="/static/img/CoinMarketCap.png" rel="apple-touch-icon"/>
<link href="/static/.bower_components/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet"/>
<script>
            var PREBID_TIMEOUT = 1500;

            var adUnits = [


                    {
                        code: 'div-gpt-ad-1488495260324-9',
                        sizes: [[728, 90]],
                        bids: [
                        {
                            "bidder": "openx",
                            "params": {
                                "unit": "539181148",
                                "delDomain": "coinmarketcap-d.openx.net" // Desktop - 728x90 ATF Detail page
                            }
                        },
                        {
                            "bidder": "appnexus",
                            "params": {
                                "placementId": "11835084" // [D] 728x90 Detail ATF: 11835084
                            }
                        },
                        {
                            "bidder": "komoona",
                            "params": {
                                "hbid": "868287e9bf904b8998fbf3d45d55d3af",
                                "placementId": "84660597a22525c53f643d470b84a8b8" // Coinmarketcap.com ABF Detail page 728x90
                            }
                        },
                        {
                            "bidder": "sovrn",
                            "params": {
                                "tagid": "496629" // CoinMarketCap_AiH_728x90_ATF_DETAILPAGE_Desktop
                            }
                        }]
                    },{
                        code: 'div-gpt-ad-1488495260324-10',
                        sizes: [[160, 600]],
                        bids: [
                        {
                            "bidder": "openx",
                            "params": {
                                "unit": "539181152",
                                "delDomain": "coinmarketcap-d.openx.net" // Desktop - 160x600 Detail page
                            }
                        },
                        {
                            "bidder": "appnexus",
                            "params": {
                                "placementId": "11835085" // [D] 160x600 Detail: 11835085
                            }
                        },
                        {
                            "bidder": "komoona",
                            "params": {
                                "hbid": "868287e9bf904b8998fbf3d45d55d3af",
                                "placementId": "0c749a3c08941c23619df0ff76b1369a" // Coinmarketcap.com Detail page 160x600
                            }
                        },
                        {
                            "bidder": "sovrn",
                            "params": {
                                "tagid": "496633" // CoinMarketCap_AiH_160x600_Side_DETAILPAGE_Desktop
                            }
                        }]
                    },{
                        code: 'div-gpt-ad-1488495260324-8',
                        sizes: [[728, 90]],
                        bids: [
                        {
                            "bidder": "openx",
                            "params": {
                                "unit": "539181150",
                                "delDomain": "coinmarketcap-d.openx.net" // Desktop - 728x90 BTF Detail page
                            }
                        },
                        {
                            "bidder": "appnexus",
                            "params": {
                                "placementId": "11835086" // [D] 728x90 Detail BTF: 11835086
                            }
                        },
                        {
                            "bidder": "komoona",
                            "params": {
                                "hbid": "868287e9bf904b8998fbf3d45d55d3af",
                                "placementId": "386e40457d4a1238421745637817317d" // Coinmarketcap.com BTF Detail page 728x90
                            }
                        },
                        {
                            "bidder": "sovrn",
                            "params": {
                                "tagid": "496631" // CoinMarketCap_AiH_728x90_BTF_DETAILPAGE_Desktop
                            }
                        }]
                    }


            ];

            var pbjs = pbjs || {};
            pbjs.que = pbjs.que || [];

            pbjs.que.push(function() {
                pbjs.setPriceGranularity("high");
                pbjs.enableSendAllBids();
            });

            pbjs.bidderSettings = {
              appnexus: {
                bidCpmAdjustment : function(bidCpm){
                  return bidCpm * 0.66;
                }
              }
            };

        </script>
<script async="async" src="/static/compressed/prebid.min.js?76ac70a3"></script>
<script async="async" src="https://www.googletagservices.com/tag/js/gpt.js"></script>
<script>
            var googletag = googletag || {};
                googletag.cmd = googletag.cmd || [];
                googletag.cmd.push(function() {
                    googletag.pubads().disableInitialLoad();
                });

            pbjs.que.push(function() {
                pbjs.addAdUnits(adUnits);
                pbjs.requestBids({
                    bidsBackHandler: sendAdserverRequest
                });
            });

            function sendAdserverRequest() {
                if (pbjs.adserverRequestSent) return;
                pbjs.adserverRequestSent = true;
                googletag.cmd.push(function() {
                    pbjs.que.push(function() {
                        pbjs.setTargetingForGPTAsync();
                        googletag.pubads().refresh();

                        var targetingParams = pbjs.getAdserverTargeting();
                        //console.log(JSON.stringify(targetingParams, null, 2));
                    });
                });
            }

            setTimeout(function() {
                sendAdserverRequest();
            }, PREBID_TIMEOUT);
        </script>
<script type="text/javascript">
          googletag.cmd.push(function() {


                    googletag.defineSlot('/48901027/non_landing_leaderboard_top', [728, 90], 'div-gpt-ad-1488495260324-9').addService(googletag.pubads());
                    googletag.defineSlot('/48901027/non_landing_side', [160, 600], 'div-gpt-ad-1488495260324-10').addService(googletag.pubads());
                    googletag.defineSlot('/48901027/non_landing_leaderboard_bottom', [728, 90], 'div-gpt-ad-1488495260324-8').addService(googletag.pubads());




                googletag.pubads().setTargeting("coin_id","1");


            googletag.pubads().enableSingleRequest();
            googletag.enableServices();
          });
        </script>
<style>
        .icobanner-close {
            color:#FFF;
        }
        #icobanner-wrapper {
            text-align:center;
            background-color:#000;
        }
    </style>
</head>
<body>
<!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
<div id="icobanner-wrapper" style="display:none">
<a href="https://bitconnect.co/" rel="nofollow" target="_blank"><img alt="bitconnect" class="icobanner-img" src="/static/sponsored/bitconnect/bitconnect2.gif"/></a>
<div class="icobanner-close">X</div>
</div>
<div id="top-nav-outer-container" role="navigation">
<div class="row">
<div class="container" id="top-nav-inner-container">
<div class="hidden-xs col-sm-3">
<div class="small" id="global-stats-counts"></div>
</div>
<div class="col-xs-12 col-sm-7">
<div class="small" id="global-stats-values"></div>
</div>
<div class="hidden-xs col-sm-2 text-right">
<div class="pull-right" id="twitter-follow">
<a class="twitter-follow-button" data-show-count="false" href="https://twitter.com/CoinMKTCap">Follow @CoinMKTCap</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</div>
</div>
</div>
</div>
</div>
<div class="container">
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-10">
<div id="title"><a href="/">CryptoCurrency Market Capitalizations</a></div>
<hr/>
<div class="text-center" id="leaderboard">
<!-- /48901027/non_landing_leaderboard_top -->
<div class="centered leaderboard" id="div-gpt-ad-1488495260324-9">
<script>
                                    googletag.cmd.push(function() { googletag.display('div-gpt-ad-1488495260324-9'); });
                                    </script>
</div>
</div>
<nav class="navbar navbar-default" id="nav-main">
<div class="navbar-header">
<button class="navbar-toggle" data-target="#navbar-collapse-1" data-toggle="collapse" type="button">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<div class="collapse navbar-collapse" id="navbar-collapse-1">
<ul class="nav navbar-nav">
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="/">Market Cap <span class="caret"></span></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/">All</a></li>
<li><a href="/currencies/">Currencies</a></li>
<li><a href="/assets/">Assets</a></li>
</ul>
</li>
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">Trade Volume <span class="caret"></span></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/currencies/volume/24-hour/">24 Hour Volume Rankings (Currency)</a></li>
<li><a href="/exchanges/volume/24-hour/">24 Hour Volume Rankings (Exchange)</a></li>
<li><a href="/currencies/volume/monthly/">Monthly Volume Rankings (Currency)</a></li>
</ul>
</li>
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">Trending <span class="caret"></span></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/gainers-losers/">Gainers and Losers</a></li>
<li><a href="/new/">Recently Added</a></li>
</ul>
</li>
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">Tools <span class="caret"></span></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/charts/">Global Charts</a></li>
<li><a href="/historical/">Historical Snapshots</a></li>
<li><a href="/calculator/">Currency Converter Calculator</a></li>
<li><a href="/widget/">Website Widgets</a></li>
</ul>
</li>
</ul>
<form action="/currencies/search/" class="navbar-form navbar-right" role="search">
<div class="form-group">
<input class="form-control js-quick-search" id="quick-search-box" name="q" placeholder="Search Currencies" type="text"/>
<button class="btn btn-primary hidden-sm hidden-md hidden-lg" type="submit"><i class="glyphicon glyphicon-search"></i></button>
</div>
<button class="btn btn-primary hidden-xs" type="submit"><i class="glyphicon glyphicon-search"></i></button>
</form>
<div class="bottom-margin-1x hidden-sm hidden-md hidden-lg"></div>
</div>
</nav>
<div class="row bottom-margin-1x">
<div class="col-xs-6 col-sm-4 col-md-4">
<h1 class="text-large"><img alt="Bitcoin" class="currency-logo-32x32" src="https://files.coinmarketcap.com/static/img/coins/32x32/bitcoin.png"/>  Bitcoin <small class="bold">(BTC)</small></h1>
</div>
<div class="col-xs-6 col-sm-8 col-md-4 text-left">
<span class="text-large" id="quote_price">$3932.79</span> <span class="text-large negative_change">(-2.80%)</span>
<br/>
<small class="text-gray">1.00 BTC</small> <small class=" positive_change "> (0.00%)</small>
<div class="row">
<div class="col-xs-12 col-sm-12 hidden-md hidden-lg text-left">
<!-- Mobile Button -->
<a href="https://changelly.com/exchange/USD/BTC/50?ref_id=coinmarketcap" target="_blank"><div class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-flash"></span> Buy / Sell Instantly</div></a>
</div>
</div>
</div>
<div class="hidden-xs hidden-sm col-md-4 text-left">
<a href="https://changelly.com/exchange/USD/BTC/50?ref_id=coinmarketcap" target="_blank"><div class="btn btn-primary"><span class="glyphicon glyphicon-flash"></span> Buy instantly with credit card</div></a>
</div>
</div>
<div class="row bottom-margin-2x">
<div class="col-xs-4 col-sm-4">
<ul class="list-unstyled">
<li><span class="glyphicon glyphicon-link text-gray" title="Website"></span> <a href="https://bitcoin.org/" target="_blank">Website</a></li>
<li><span class="glyphicon glyphicon-link text-gray" title="Website"></span> <a href="https://www.bitcoin.com/" target="_blank">Website 2</a></li>
<li><span class="glyphicon glyphicon-search text-gray" title="Explorer"></span> <a href="http://blockchain.info" target="_blank">Explorer</a></li>
<li><span class="glyphicon glyphicon-search text-gray" title="Explorer"></span> <a href="https://blockexplorer.com/" target="_blank">Explorer 2</a></li>
<li><span class="glyphicon glyphicon-list text-gray" title="Message Board"></span> <a href="https://bitcointalk.org" target="_blank">Message Board</a></li>
<li><span class="glyphicon glyphicon-list text-gray" title="Message Board"></span> <a href="https://forum.bitcoin.com/" target="_blank">Message Board 2</a></li>
<li><span class="glyphicon glyphicon glyphicon-star text-gray" title="Rank"></span>
<small><span class="label label-success"> Rank 1</span></small>
</li>
<li><span class="glyphicon glyphicon glyphicon-tag text-gray" title="Tags"></span>
<small><span class="label label-warning">Mineable</span></small>
<small><span class="label label-warning">Currency</span></small>
</li>
</ul>
</div>
<div class="col-xs-8 col-sm-8">
<div class="coin-summary-item col-xs-6 col-md-3">
<div class="coin-summary-item-header">
<h3>Market Cap</h3>
</div>
<div class="coin-summary-item-detail">
                      $65,190,221,999 <br/>
<span class="text-gray">16,576,075 BTC</span> <br/>
</div>
</div>
<div class="coin-summary-item col-xs-6 col-md-3">
<div class="coin-summary-item-header">
<h3>Volume (24h)</h3>
</div>
<div class="coin-summary-item-detail">
                      $1,573,990,000<br/>
<span class="text-gray">400,879 BTC</span>
</div>
</div>
<div class="vertical-spacer col-xs-12 hidden-md hidden-lg"></div>
<div class="coin-summary-item col-xs-6 col-md-3">
<div class="coin-summary-item-header">
<h3>Circulating Supply</h3>
</div>
<div class="coin-summary-item-detail">
                      16,576,075 BTC
                    </div>
</div>
<div class="coin-summary-item col-xs-6 col-md-3 ">
<div class="coin-summary-item-header">
<h3>Max Supply</h3>
</div>
<div class="coin-summary-item-detail">
                    21,000,000 BTC
                  </div>
</div>
</div>
</div>
<div class="row bottom-margin-1x">
<div class="col-xs-12">
<ul class="nav nav-tabs text-left" role="tablist">
<li><a href="/currencies/bitcoin/#charts"> <span class="glyphicon glyphicon-stats text-gray"></span> Charts </a></li>
<li><a href="/currencies/bitcoin/#markets"><span class="glyphicon glyphicon-transfer text-gray"></span> Markets </a></li>
<li><a href="/currencies/bitcoin/#social"><span class="glyphicon glyphicon-globe text-gray"></span> Social </a></li>
<li><a href="/currencies/bitcoin/#tools"><span class="glyphicon glyphicon-wrench text-gray"></span> Tools </a></li>
<li class="active"><a href="/currencies/bitcoin/historical-data/"><span class="glyphicon glyphicon-calendar text-gray"></span> Historical Data </a></li>
</ul>
</div>
<div class="col-xs-12 tab-content">
<div class="tab-pane active" id="historical-data">
<div class="tab-header">
<h2 class="pull-left bottom-margin-2x">Historical data for Bitcoin</h2>
<div class="clear"></div>
<div class="row">
<div class="col-md-12">
<div class="pull-left">
<small>Currency in USD</small>
</div>
<div class="pull-right" id="reportrange">
<i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                        <span></span> <b class="caret"></b>
</div>
</div>
</div>
<table class="table">
<thead>
<tr>
<th class="text-left">Date</th>
<th class="text-right">Open</th>
<th class="text-right">High</th>
<th class="text-right">Low</th>
<th class="text-right">Close</th>
<th class="text-right">Volume</th>
<th class="text-right">Market Cap</th>
</tr>
</thead>
<tbody>
<tr class="text-right">
<td class="text-left">Sep 18, 2017</td>
<td>3591.09</td>
<td>4079.23</td>
<td>3591.09</td>
<td>4065.20</td>
<td>1,943,210,000</td>
<td>59,514,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 17, 2017</td>
<td>3606.28</td>
<td>3664.81</td>
<td>3445.64</td>
<td>3582.88</td>
<td>1,239,150,000</td>
<td>59,757,800,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 16, 2017</td>
<td>3637.75</td>
<td>3808.84</td>
<td>3487.79</td>
<td>3625.04</td>
<td>1,818,400,000</td>
<td>60,271,600,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 15, 2017</td>
<td>3166.30</td>
<td>3733.45</td>
<td>2946.62</td>
<td>3637.52</td>
<td>4,148,070,000</td>
<td>52,453,500,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 14, 2017</td>
<td>3875.37</td>
<td>3920.60</td>
<td>3153.86</td>
<td>3154.95</td>
<td>2,716,310,000</td>
<td>64,191,600,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 13, 2017</td>
<td>4131.98</td>
<td>4131.98</td>
<td>3789.92</td>
<td>3882.59</td>
<td>2,219,410,000</td>
<td>68,432,200,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 12, 2017</td>
<td>4168.88</td>
<td>4344.65</td>
<td>4085.22</td>
<td>4130.81</td>
<td>1,864,530,000</td>
<td>69,033,400,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 11, 2017</td>
<td>4122.47</td>
<td>4261.67</td>
<td>4099.40</td>
<td>4161.27</td>
<td>1,557,330,000</td>
<td>68,256,000,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 10, 2017</td>
<td>4229.34</td>
<td>4245.44</td>
<td>3951.04</td>
<td>4122.94</td>
<td>1,679,090,000</td>
<td>70,018,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 09, 2017</td>
<td>4229.81</td>
<td>4308.82</td>
<td>4114.11</td>
<td>4226.06</td>
<td>1,386,230,000</td>
<td>70,017,200,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 08, 2017</td>
<td>4605.16</td>
<td>4661.00</td>
<td>4075.18</td>
<td>4228.75</td>
<td>2,700,890,000</td>

<body>
<!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
<div id="icobanner-wrapper" style="display:none">
<a href="https://bitconnect.co/" rel="nofollow" target="_blank"><img alt="bitconnect" class="icobanner-img" src="/static/sponsored/bitconnect/bitconnect2.gif"/></a>
<div class="icobanner-close">X</div>
</div>
<div id="top-nav-outer-container" role="navigation">
<div class="row">
<div class="container" id="top-nav-inner-container">
<div class="hidden-xs col-sm-3">
<div class="small" id="global-stats-counts"></div>
</div>
<div class="col-xs-12 col-sm-7">
<div class="small" id="global-stats-values"></div>
</div>
<div class="hidden-xs col-sm-2 text-right">
<div class="pull-right" id="twitter-follow">
<a class="twitter-follow-button" data-show-count="false" href="https://twitter.com/CoinMKTCap">Follow @CoinMKTCap</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</div>
</div>
</div>
</div>
</div>
<div class="container">
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-10">
<div id="title"><a href="/">CryptoCurrency Market Capitalizations</a></div>
<hr/>
<div class="text-center" id="leaderboard">
<!-- /48901027/non_landing_leaderboard_top -->
<div class="centered leaderboard" id="div-gpt-ad-1488495260324-9">
<script>
                                    googletag.cmd.push(function() { googletag.display('div-gpt-ad-1488495260324-9'); });
                                    </script>
</div>
</div>
<nav class="navbar navbar-default" id="nav-main">
<div class="navbar-header">
<button class="navbar-toggle" data-target="#navbar-collapse-1" data-toggle="collapse" type="button">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<div class="collapse navbar-collapse" id="navbar-collapse-1">
<ul class="nav navbar-nav">
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="/">Market Cap <span class="caret"></span></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/">All</a></li>
<li><a href="/currencies/">Currencies</a></li>
<li><a href="/assets/">Assets</a></li>
</ul>
</li>
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">Trade Volume <span class="caret"></span></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/currencies/volume/24-hour/">24 Hour Volume Rankings (Currency)</a></li>
<li><a href="/exchanges/volume/24-hour/">24 Hour Volume Rankings (Exchange)</a></li>
<li><a href="/currencies/volume/monthly/">Monthly Volume Rankings (Currency)</a></li>
</ul>
</li>
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">Trending <span class="caret"></span></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/gainers-losers/">Gainers and Losers</a></li>
<li><a href="/new/">Recently Added</a></li>
</ul>
</li>
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">Tools <span class="caret"></span></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/charts/">Global Charts</a></li>
<li><a href="/historical/">Historical Snapshots</a></li>
<li><a href="/calculator/">Currency Converter Calculator</a></li>
<li><a href="/widget/">Website Widgets</a></li>
</ul>
</li>
</ul>
<form action="/currencies/search/" class="navbar-form navbar-right" role="search">
<div class="form-group">
<input class="form-control js-quick-search" id="quick-search-box" name="q" placeholder="Search Currencies" type="text"/>
<button class="btn btn-primary hidden-sm hidden-md hidden-lg" type="submit"><i class="glyphicon glyphicon-search"></i></button>
</div>
<button class="btn btn-primary hidden-xs" type="submit"><i class="glyphicon glyphicon-search"></i></button>
</form>
<div class="bottom-margin-1x hidden-sm hidden-md hidden-lg"></div>
</div>
</nav>
<div class="row bottom-margin-1x">
<div class="col-xs-6 col-sm-4 col-md-4">
<h1 class="text-large"><img alt="Bitcoin" class="currency-logo-32x32" src="https://files.coinmarketcap.com/static/img/coins/32x32/bitcoin.png"/>  Bitcoin <small class="bold">(BTC)</small></h1>
</div>
<div class="col-xs-6 col-sm-8 col-md-4 text-left">
<span class="text-large" id="quote_price">$3932.79</span> <span class="text-large negative_change">(-2.80%)</span>
<br/>
<small class="text-gray">1.00 BTC</small> <small class=" positive_change "> (0.00%)</small>
<div class="row">
<div class="col-xs-12 col-sm-12 hidden-md hidden-lg text-left">
<!-- Mobile Button -->
<a href="https://changelly.com/exchange/USD/BTC/50?ref_id=coinmarketcap" target="_blank"><div class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-flash"></span> Buy / Sell Instantly</div></a>
</div>
</div>
</div>
<div class="hidden-xs hidden-sm col-md-4 text-left">
<a href="https://changelly.com/exchange/USD/BTC/50?ref_id=coinmarketcap" target="_blank"><div class="btn btn-primary"><span class="glyphicon glyphicon-flash"></span> Buy instantly with credit card</div></a>
</div>
</div>
<div class="row bottom-margin-2x">
<div class="col-xs-4 col-sm-4">
<ul class="list-unstyled">
<li><span class="glyphicon glyphicon-link text-gray" title="Website"></span> <a href="https://bitcoin.org/" target="_blank">Website</a></li>
<li><span class="glyphicon glyphicon-link text-gray" title="Website"></span> <a href="https://www.bitcoin.com/" target="_blank">Website 2</a></li>
<li><span class="glyphicon glyphicon-search text-gray" title="Explorer"></span> <a href="http://blockchain.info" target="_blank">Explorer</a></li>
<li><span class="glyphicon glyphicon-search text-gray" title="Explorer"></span> <a href="https://blockexplorer.com/" target="_blank">Explorer 2</a></li>
<li><span class="glyphicon glyphicon-list text-gray" title="Message Board"></span> <a href="https://bitcointalk.org" target="_blank">Message Board</a></li>
<li><span class="glyphicon glyphicon-list text-gray" title="Message Board"></span> <a href="https://forum.bitcoin.com/" target="_blank">Message Board 2</a></li>
<li><span class="glyphicon glyphicon glyphicon-star text-gray" title="Rank"></span>
<small><span class="label label-success"> Rank 1</span></small>
</li>
<li><span class="glyphicon glyphicon glyphicon-tag text-gray" title="Tags"></span>
<small><span class="label label-warning">Mineable</span></small>
<small><span class="label label-warning">Currency</span></small>
</li>
</ul>
</div>
<div class="col-xs-8 col-sm-8">
<div class="coin-summary-item col-xs-6 col-md-3">
<div class="coin-summary-item-header">
<h3>Market Cap</h3>
</div>
<div class="coin-summary-item-detail">
                      $65,190,221,999 <br/>
<span class="text-gray">16,576,075 BTC</span> <br/>
</div>
</div>
<div class="coin-summary-item col-xs-6 col-md-3">
<div class="coin-summary-item-header">
<h3>Volume (24h)</h3>
</div>
<div class="coin-summary-item-detail">
                      $1,573,990,000<br/>
<span class="text-gray">400,879 BTC</span>
</div>
</div>
<div class="vertical-spacer col-xs-12 hidden-md hidden-lg"></div>
<div class="coin-summary-item col-xs-6 col-md-3">
<div class="coin-summary-item-header">
<h3>Circulating Supply</h3>
</div>
<div class="coin-summary-item-detail">
                      16,576,075 BTC
                    </div>
</div>
<div class="coin-summary-item col-xs-6 col-md-3 ">
<div class="coin-summary-item-header">
<h3>Max Supply</h3>
</div>
<div class="coin-summary-item-detail">
                    21,000,000 BTC
                  </div>
</div>
</div>
</div>
<div class="row bottom-margin-1x">
<div class="col-xs-12">
<ul class="nav nav-tabs text-left" role="tablist">
<li><a href="/currencies/bitcoin/#charts"> <span class="glyphicon glyphicon-stats text-gray"></span> Charts </a></li>
<li><a href="/currencies/bitcoin/#markets"><span class="glyphicon glyphicon-transfer text-gray"></span> Markets </a></li>
<li><a href="/currencies/bitcoin/#social"><span class="glyphicon glyphicon-globe text-gray"></span> Social </a></li>
<li><a href="/currencies/bitcoin/#tools"><span class="glyphicon glyphicon-wrench text-gray"></span> Tools </a></li>
<li class="active"><a href="/currencies/bitcoin/historical-data/"><span class="glyphicon glyphicon-calendar text-gray"></span> Historical Data </a></li>
</ul>
</div>
<div class="col-xs-12 tab-content">
<div class="tab-pane active" id="historical-data">
<div class="tab-header">
<h2 class="pull-left bottom-margin-2x">Historical data for Bitcoin</h2>
<div class="clear"></div>
<div class="row">
<div class="col-md-12">
<div class="pull-left">
<small>Currency in USD</small>
</div>
<div class="pull-right" id="reportrange">
<i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                        <span></span> <b class="caret"></b>
</div>
</div>
</div>
<table class="table">
<thead>
<tr>
<th class="text-left">Date</th>
<th class="text-right">Open</th>
<th class="text-right">High</th>
<th class="text-right">Low</th>
<th class="text-right">Close</th>
<th class="text-right">Volume</th>
<th class="text-right">Market Cap</th>
</tr>
</thead>
<tbody>
<tr class="text-right">
<td class="text-left">Sep 18, 2017</td>
<td>3591.09</td>
<td>4079.23</td>
<td>3591.09</td>
<td>4065.20</td>
<td>1,943,210,000</td>
<td>59,514,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 17, 2017</td>
<td>3606.28</td>
<td>3664.81</td>
<td>3445.64</td>
<td>3582.88</td>
<td>1,239,150,000</td>
<td>59,757,800,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 16, 2017</td>
<td>3637.75</td>
<td>3808.84</td>
<td>3487.79</td>
<td>3625.04</td>
<td>1,818,400,000</td>
<td>60,271,600,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 15, 2017</td>
<td>3166.30</td>
<td>3733.45</td>
<td>2946.62</td>
<td>3637.52</td>
<td>4,148,070,000</td>
<td>52,453,500,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 14, 2017</td>
<td>3875.37</td>
<td>3920.60</td>
<td>3153.86</td>
<td>3154.95</td>
<td>2,716,310,000</td>
<td>64,191,600,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 13, 2017</td>
<td>4131.98</td>
<td>4131.98</td>
<td>3789.92</td>
<td>3882.59</td>
<td>2,219,410,000</td>
<td>68,432,200,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 12, 2017</td>
<td>4168.88</td>
<td>4344.65</td>
<td>4085.22</td>
<td>4130.81</td>
<td>1,864,530,000</td>
<td>69,033,400,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 11, 2017</td>
<td>4122.47</td>
<td>4261.67</td>
<td>4099.40</td>
<td>4161.27</td>
<td>1,557,330,000</td>
<td>68,256,000,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 10, 2017</td>
<td>4229.34</td>
<td>4245.44</td>
<td>3951.04</td>
<td>4122.94</td>
<td>1,679,090,000</td>
<td>70,018,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 09, 2017</td>
<td>4229.81</td>
<td>4308.82</td>
<td>4114.11</td>
<td>4226.06</td>
<td>1,386,230,000</td>
<td>70,017,200,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 08, 2017</td>
<td>4605.16</td>
<td>4661.00</td>
<td>4075.18</td>
<td>4228.75</td>
<td>2,700,890,000</td>
<td>76,220,200,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 07, 2017</td>
<td>4589.14</td>
<td>4655.04</td>
<td>4491.33</td>
<td>4599.88</td>
<td>1,844,620,000</td>
<td>75,945,000,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 06, 2017</td>
<td>4376.59</td>
<td>4617.25</td>
<td>4376.59</td>
<td>4597.12</td>
<td>2,172,100,000</td>
<td>72,418,700,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 05, 2017</td>
<td>4228.29</td>
<td>4427.84</td>
<td>3998.11</td>
<td>4376.53</td>
<td>2,697,970,000</td>
<td>69,954,400,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 04, 2017</td>
<td>4591.63</td>
<td>4591.63</td>
<td>4108.40</td>
<td>4236.31</td>
<td>2,987,330,000</td>
<td>75,955,500,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 03, 2017</td>
<td>4585.27</td>
<td>4714.08</td>
<td>4417.59</td>
<td>4582.96</td>
<td>1,933,190,000</td>
<td>75,841,700,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 02, 2017</td>
<td>4901.42</td>
<td>4975.04</td>
<td>4469.24</td>
<td>4578.77</td>
<td>2,722,140,000</td>
<td>81,060,600,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 01, 2017</td>
<td>4701.76</td>
<td>4892.01</td>
<td>4678.53</td>
<td>4892.01</td>
<td>2,599,080,000</td>
<td>77,748,400,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 31, 2017</td>
<td>4555.59</td>
<td>4736.05</td>
<td>4549.40</td>
<td>4703.39</td>
<td>1,944,930,000</td>
<td>75,322,300,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 30, 2017</td>
<td>4570.36</td>
<td>4626.52</td>
<td>4471.41</td>
<td>4565.30</td>
<td>1,937,850,000</td>
<td>75,556,600,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 29, 2017</td>
<td>4389.21</td>
<td>4625.68</td>
<td>4352.13</td>
<td>4579.02</td>
<td>2,486,080,000</td>
<td>72,553,800,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 28, 2017</td>
<td>4384.45</td>
<td>4403.93</td>
<td>4224.64</td>
<td>4382.66</td>
<td>1,959,330,000</td>
<td>72,467,900,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 27, 2017</td>
<td>4345.10</td>
<td>4416.59</td>
<td>4317.29</td>
<td>4382.88</td>
<td>1,537,460,000</td>
<td>71,809,200,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 26, 2017</td>
<td>4372.06</td>
<td>4379.28</td>
<td>4269.52</td>
<td>4352.40</td>
<td>1,511,610,000</td>
<td>72,249,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 25, 2017</td>
<td>4332.82</td>
<td>4455.70</td>
<td>4307.35</td>
<td>4371.60</td>
<td>1,727,970,000</td>
<td>71,595,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 24, 2017</td>
<td>4137.60</td>
<td>4376.39</td>
<td>4130.26</td>
<td>4334.68</td>
<td>2,037,750,000</td>
<td>68,363,900,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 23, 2017</td>
<td>4089.01</td>
<td>4255.78</td>
<td>4078.41</td>
<td>4151.52</td>
<td>2,369,820,000</td>
<td>67,553,000,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 22, 2017</td>
<td>3998.35</td>
<td>4128.76</td>
<td>3674.58</td>
<td>4100.52</td>
<td>3,764,240,000</td>
<td>66,051,000,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 21, 2017</td>
<td>4090.48</td>
<td>4109.14</td>
<td>3988.60</td>
<td>4001.74</td>
<td>2,800,890,000</td>
<td>67,567,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 20, 2017</td>
<td>4189.31</td>
<td>4196.29</td>
<td>4069.88</td>
<td>4087.66</td>
<td>2,109,770,000</td>
<td>69,192,700,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 19, 2017</td>
<td>4137.75</td>
<td>4243.26</td>
<td>3970.55</td>
<td>4193.70</td>
<td>2,975,820,000</td>
<td>68,333,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 18, 2017</td>
<td>4324.34</td>
<td>4370.13</td>
<td>4015.40</td>
<td>4160.62</td>
<td>2,941,710,000</td>
<td>71,406,500,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 17, 2017</td>
<td>4384.44</td>
<td>4484.70</td>
<td>4243.71</td>
<td>4331.69</td>
<td>2,553,360,000</td>
<td>72,389,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 16, 2017</td>
<td>4200.34</td>
<td>4381.23</td>
<td>3994.42</td>
<td>4376.63</td>
<td>2,272,040,000</td>
<td>69,342,700,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 15, 2017</td>
<td>4326.99</td>
<td>4455.97</td>
<td>3906.18</td>
<td>4181.93</td>
<td>3,258,050,000</td>
<td>71,425,500,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 14, 2017</td>
<td>4066.10</td>
<td>4325.13</td>
<td>3989.16</td>
<td>4325.13</td>
<td>2,463,090,000</td>
<td>67,112,300,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 13, 2017</td>
<td>3880.04</td>
<td>4208.39</td>
<td>3857.80</td>
<td>4073.26</td>
<td>3,159,090,000</td>
<td>64,034,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 12, 2017</td>
<td>3650.63</td>
<td>3949.92</td>
<td>3613.70</td>
<td>3884.71</td>
<td>2,219,590,000</td>
<td>60,242,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 11, 2017</td>
<td>3373.82</td>
<td>3679.72</td>
<td>3372.12</td>
<td>3650.62</td>
<td>2,021,190,000</td>
<td>55,668,000,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 10, 2017</td>
<td>3341.84</td>
<td>3453.45</td>
<td>3319.47</td>
<td>3381.28</td>
<td>1,515,110,000</td>
<td>55,134,700,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 09, 2017</td>
<td>3420.40</td>
<td>3422.76</td>
<td>3247.67</td>
<td>3342.47</td>
<td>1,468,960,000</td>
<td>56,424,900,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 08, 2017</td>
<td>3370.22</td>
<td>3484.85</td>
<td>3345.83</td>
<td>3419.94</td>
<td>1,752,760,000</td>
<td>55,590,300,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 07, 2017</td>
<td>3212.78</td>
<td>3397.68</td>
<td>3180.89</td>
<td>3378.94</td>
<td>1,482,280,000</td>
<td>52,987,300,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 06, 2017</td>
<td>3257.61</td>
<td>3293.29</td>
<td>3155.60</td>
<td>3213.94</td>
<td>1,105,030,000</td>
<td>53,720,900,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 05, 2017</td>
<td>2897.63</td>
<td>3290.01</td>
<td>2874.83</td>
<td>3252.91</td>
<td>1,945,700,000</td>
<td>47,778,200,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 04, 2017</td>
<td>2806.93</td>
<td>2899.33</td>
<td>2743.72</td>
<td>2895.89</td>
<td>1,002,120,000</td>
<td>46,276,200,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 03, 2017</td>
<td>2709.56</td>
<td>2813.31</td>
<td>2685.14</td>
<td>2804.73</td>
<td>804,797,000</td>
<td>44,666,400,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 02, 2017</td>
<td>2727.13</td>
<td>2762.53</td>
<td>2668.59</td>
<td>2710.67</td>
<td>1,094,950,000</td>
<td>44,950,800,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 01, 2017</td>
<td>2871.30</td>
<td>2921.35</td>
<td>2685.61</td>
<td>2718.26</td>
<td>1,324,670,000</td>
<td>47,321,800,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 31, 2017</td>
<td>2763.24</td>
<td>2889.62</td>
<td>2720.61</td>
<td>2875.34</td>
<td>860,575,000</td>
<td>45,535,800,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 30, 2017</td>
<td>2724.39</td>
<td>2758.53</td>
<td>2644.85</td>
<td>2757.18</td>
<td>705,943,000</td>
<td>44,890,700,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 29, 2017</td>
<td>2807.02</td>
<td>2808.76</td>
<td>2692.80</td>
<td>2726.45</td>
<td>803,746,000</td>
<td>46,246,700,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 28, 2017</td>
<td>2679.73</td>
<td>2897.45</td>
<td>2679.73</td>
<td>2809.01</td>
<td>1,380,100,000</td>
<td>44,144,400,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 27, 2017</td>
<td>2538.71</td>
<td>2693.32</td>
<td>2529.34</td>
<td>2671.78</td>
<td>789,104,000</td>
<td>41,816,500,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 26, 2017</td>
<td>2577.77</td>
<td>2610.76</td>
<td>2450.80</td>
<td>2529.45</td>
<td>937,404,000</td>
<td>42,455,000,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 25, 2017</td>
<td>2757.50</td>
<td>2768.08</td>
<td>2480.96</td>
<td>2576.48</td>
<td>1,460,090,000</td>
<td>45,410,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 24, 2017</td>
<td>2732.70</td>
<td>2777.26</td>
<td>2699.19</td>
<td>2754.86</td>
<td>866,474,000</td>

<div class="container">
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-10">
<div id="title"><a href="/">CryptoCurrency Market Capitalizations</a></div>
<hr/>
<div class="text-center" id="leaderboard">
<!-- /48901027/non_landing_leaderboard_top -->
<div class="centered leaderboard" id="div-gpt-ad-1488495260324-9">
<script>
                                    googletag.cmd.push(function() { googletag.display('div-gpt-ad-1488495260324-9'); });
                                    </script>
</div>
</div>
<nav class="navbar navbar-default" id="nav-main">
<div class="navbar-header">
<button class="navbar-toggle" data-target="#navbar-collapse-1" data-toggle="collapse" type="button">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<div class="collapse navbar-collapse" id="navbar-collapse-1">
<ul class="nav navbar-nav">
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="/">Market Cap <span class="caret"></span></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/">All</a></li>
<li><a href="/currencies/">Currencies</a></li>
<li><a href="/assets/">Assets</a></li>
</ul>
</li>
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">Trade Volume <span class="caret"></span></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/currencies/volume/24-hour/">24 Hour Volume Rankings (Currency)</a></li>
<li><a href="/exchanges/volume/24-hour/">24 Hour Volume Rankings (Exchange)</a></li>
<li><a href="/currencies/volume/monthly/">Monthly Volume Rankings (Currency)</a></li>
</ul>
</li>
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">Trending <span class="caret"></span></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/gainers-losers/">Gainers and Losers</a></li>
<li><a href="/new/">Recently Added</a></li>
</ul>
</li>
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">Tools <span class="caret"></span></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/charts/">Global Charts</a></li>
<li><a href="/historical/">Historical Snapshots</a></li>
<li><a href="/calculator/">Currency Converter Calculator</a></li>
<li><a href="/widget/">Website Widgets</a></li>
</ul>
</li>
</ul>
<form action="/currencies/search/" class="navbar-form navbar-right" role="search">
<div class="form-group">
<input class="form-control js-quick-search" id="quick-search-box" name="q" placeholder="Search Currencies" type="text"/>
<button class="btn btn-primary hidden-sm hidden-md hidden-lg" type="submit"><i class="glyphicon glyphicon-search"></i></button>
</div>
<button class="btn btn-primary hidden-xs" type="submit"><i class="glyphicon glyphicon-search"></i></button>
</form>
<div class="bottom-margin-1x hidden-sm hidden-md hidden-lg"></div>
</div>
</nav>
<div class="row bottom-margin-1x">
<div class="col-xs-6 col-sm-4 col-md-4">
<h1 class="text-large"><img alt="Bitcoin" class="currency-logo-32x32" src="https://files.coinmarketcap.com/static/img/coins/32x32/bitcoin.png"/>  Bitcoin <small class="bold">(BTC)</small></h1>
</div>
<div class="col-xs-6 col-sm-8 col-md-4 text-left">
<span class="text-large" id="quote_price">$3932.79</span> <span class="text-large negative_change">(-2.80%)</span>
<br/>
<small class="text-gray">1.00 BTC</small> <small class=" positive_change "> (0.00%)</small>
<div class="row">
<div class="col-xs-12 col-sm-12 hidden-md hidden-lg text-left">
<!-- Mobile Button -->
<a href="https://changelly.com/exchange/USD/BTC/50?ref_id=coinmarketcap" target="_blank"><div class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-flash"></span> Buy / Sell Instantly</div></a>
</div>
</div>
</div>
<div class="hidden-xs hidden-sm col-md-4 text-left">
<a href="https://changelly.com/exchange/USD/BTC/50?ref_id=coinmarketcap" target="_blank"><div class="btn btn-primary"><span class="glyphicon glyphicon-flash"></span> Buy instantly with credit card</div></a>
</div>
</div>
<div class="row bottom-margin-2x">
<div class="col-xs-4 col-sm-4">
<ul class="list-unstyled">
<li><span class="glyphicon glyphicon-link text-gray" title="Website"></span> <a href="https://bitcoin.org/" target="_blank">Website</a></li>
<li><span class="glyphicon glyphicon-link text-gray" title="Website"></span> <a href="https://www.bitcoin.com/" target="_blank">Website 2</a></li>
<li><span class="glyphicon glyphicon-search text-gray" title="Explorer"></span> <a href="http://blockchain.info" target="_blank">Explorer</a></li>
<li><span class="glyphicon glyphicon-search text-gray" title="Explorer"></span> <a href="https://blockexplorer.com/" target="_blank">Explorer 2</a></li>
<li><span class="glyphicon glyphicon-list text-gray" title="Message Board"></span> <a href="https://bitcointalk.org" target="_blank">Message Board</a></li>
<li><span class="glyphicon glyphicon-list text-gray" title="Message Board"></span> <a href="https://forum.bitcoin.com/" target="_blank">Message Board 2</a></li>
<li><span class="glyphicon glyphicon glyphicon-star text-gray" title="Rank"></span>
<small><span class="label label-success"> Rank 1</span></small>
</li>
<li><span class="glyphicon glyphicon glyphicon-tag text-gray" title="Tags"></span>
<small><span class="label label-warning">Mineable</span></small>
<small><span class="label label-warning">Currency</span></small>
</li>
</ul>
</div>
<div class="col-xs-8 col-sm-8">
<div class="coin-summary-item col-xs-6 col-md-3">
<div class="coin-summary-item-header">
<h3>Market Cap</h3>
</div>
<div class="coin-summary-item-detail">
                      $65,190,221,999 <br/>
<span class="text-gray">16,576,075 BTC</span> <br/>
</div>
</div>
<div class="coin-summary-item col-xs-6 col-md-3">
<div class="coin-summary-item-header">
<h3>Volume (24h)</h3>
</div>
<div class="coin-summary-item-detail">
                      $1,573,990,000<br/>
<span class="text-gray">400,879 BTC</span>
</div>
</div>
<div class="vertical-spacer col-xs-12 hidden-md hidden-lg"></div>
<div class="coin-summary-item col-xs-6 col-md-3">
<div class="coin-summary-item-header">
<h3>Circulating Supply</h3>
</div>
<div class="coin-summary-item-detail">
                      16,576,075 BTC
                    </div>
</div>
<div class="coin-summary-item col-xs-6 col-md-3 ">
<div class="coin-summary-item-header">
<h3>Max Supply</h3>
</div>
<div class="coin-summary-item-detail">
                    21,000,000 BTC
                  </div>
</div>
</div>
</div>
<div class="row bottom-margin-1x">
<div class="col-xs-12">
<ul class="nav nav-tabs text-left" role="tablist">
<li><a href="/currencies/bitcoin/#charts"> <span class="glyphicon glyphicon-stats text-gray"></span> Charts </a></li>
<li><a href="/currencies/bitcoin/#markets"><span class="glyphicon glyphicon-transfer text-gray"></span> Markets </a></li>
<li><a href="/currencies/bitcoin/#social"><span class="glyphicon glyphicon-globe text-gray"></span> Social </a></li>
<li><a href="/currencies/bitcoin/#tools"><span class="glyphicon glyphicon-wrench text-gray"></span> Tools </a></li>
<li class="active"><a href="/currencies/bitcoin/historical-data/"><span class="glyphicon glyphicon-calendar text-gray"></span> Historical Data </a></li>
</ul>
</div>
<div class="col-xs-12 tab-content">
<div class="tab-pane active" id="historical-data">
<div class="tab-header">
<h2 class="pull-left bottom-margin-2x">Historical data for Bitcoin</h2>
<div class="clear"></div>
<div class="row">
<div class="col-md-12">
<div class="pull-left">
<small>Currency in USD</small>
</div>
<div class="pull-right" id="reportrange">
<i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                        <span></span> <b class="caret"></b>
</div>
</div>
</div>
<table class="table">
<thead>
<tr>
<th class="text-left">Date</th>
<th class="text-right">Open</th>
<th class="text-right">High</th>
<th class="text-right">Low</th>
<th class="text-right">Close</th>
<th class="text-right">Volume</th>
<th class="text-right">Market Cap</th>
</tr>
</thead>
<tbody>
<tr class="text-right">
<td class="text-left">Sep 18, 2017</td>
<td>3591.09</td>
<td>4079.23</td>
<td>3591.09</td>
<td>4065.20</td>
<td>1,943,210,000</td>
<td>59,514,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 17, 2017</td>
<td>3606.28</td>
<td>3664.81</td>
<td>3445.64</td>
<td>3582.88</td>
<td>1,239,150,000</td>
<td>59,757,800,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 16, 2017</td>
<td>3637.75</td>
<td>3808.84</td>
<td>3487.79</td>
<td>3625.04</td>
<td>1,818,400,000</td>
<td>60,271,600,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 15, 2017</td>
<td>3166.30</td>
<td>3733.45</td>
<td>2946.62</td>
<td>3637.52</td>
<td>4,148,070,000</td>
<td>52,453,500,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 14, 2017</td>
<td>3875.37</td>
<td>3920.60</td>
<td>3153.86</td>
<td>3154.95</td>
<td>2,716,310,000</td>
<td>64,191,600,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 13, 2017</td>
<td>4131.98</td>
<td>4131.98</td>
<td>3789.92</td>
<td>3882.59</td>
<td>2,219,410,000</td>
<td>68,432,200,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 12, 2017</td>
<td>4168.88</td>
<td>4344.65</td>
<td>4085.22</td>
<td>4130.81</td>
<td>1,864,530,000</td>
<td>69,033,400,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 11, 2017</td>
<td>4122.47</td>
<td>4261.67</td>
<td>4099.40</td>
<td>4161.27</td>
<td>1,557,330,000</td>
<td>68,256,000,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 10, 2017</td>
<td>4229.34</td>
<td>4245.44</td>
<td>3951.04</td>
<td>4122.94</td>
<td>1,679,090,000</td>
<td>70,018,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 09, 2017</td>
<td>4229.81</td>
<td>4308.82</td>
<td>4114.11</td>
<td>4226.06</td>
<td>1,386,230,000</td>
<td>70,017,200,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 08, 2017</td>
<td>4605.16</td>
<td>4661.00</td>
<td>4075.18</td>
<td>4228.75</td>
<td>2,700,890,000</td>
<td>76,220,200,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 07, 2017</td>
<td>4589.14</td>
<td>4655.04</td>
<td>4491.33</td>
<td>4599.88</td>
<td>1,844,620,000</td>
<td>75,945,000,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 06, 2017</td>
<td>4376.59</td>
<td>4617.25</td>
<td>4376.59</td>
<td>4597.12</td>
<td>2,172,100,000</td>
<td>72,418,700,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 05, 2017</td>
<td>4228.29</td>
<td>4427.84</td>
<td>3998.11</td>
<td>4376.53</td>
<td>2,697,970,000</td>
<td>69,954,400,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 04, 2017</td>
<td>4591.63</td>
<td>4591.63</td>
<td>4108.40</td>
<td>4236.31</td>
<td>2,987,330,000</td>
<td>75,955,500,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 03, 2017</td>
<td>4585.27</td>
<td>4714.08</td>
<td>4417.59</td>
<td>4582.96</td>
<td>1,933,190,000</td>
<td>75,841,700,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 02, 2017</td>
<td>4901.42</td>
<td>4975.04</td>
<td>4469.24</td>
<td>4578.77</td>
<td>2,722,140,000</td>
<td>81,060,600,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Sep 01, 2017</td>
<td>4701.76</td>
<td>4892.01</td>
<td>4678.53</td>
<td>4892.01</td>
<td>2,599,080,000</td>
<td>77,748,400,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 31, 2017</td>
<td>4555.59</td>
<td>4736.05</td>
<td>4549.40</td>
<td>4703.39</td>
<td>1,944,930,000</td>
<td>75,322,300,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 30, 2017</td>
<td>4570.36</td>
<td>4626.52</td>
<td>4471.41</td>
<td>4565.30</td>
<td>1,937,850,000</td>
<td>75,556,600,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 29, 2017</td>
<td>4389.21</td>
<td>4625.68</td>
<td>4352.13</td>
<td>4579.02</td>
<td>2,486,080,000</td>
<td>72,553,800,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 28, 2017</td>
<td>4384.45</td>
<td>4403.93</td>
<td>4224.64</td>
<td>4382.66</td>
<td>1,959,330,000</td>
<td>72,467,900,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 27, 2017</td>
<td>4345.10</td>
<td>4416.59</td>
<td>4317.29</td>
<td>4382.88</td>
<td>1,537,460,000</td>
<td>71,809,200,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 26, 2017</td>
<td>4372.06</td>
<td>4379.28</td>
<td>4269.52</td>
<td>4352.40</td>
<td>1,511,610,000</td>
<td>72,249,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 25, 2017</td>
<td>4332.82</td>
<td>4455.70</td>
<td>4307.35</td>
<td>4371.60</td>
<td>1,727,970,000</td>
<td>71,595,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 24, 2017</td>
<td>4137.60</td>
<td>4376.39</td>
<td>4130.26</td>
<td>4334.68</td>
<td>2,037,750,000</td>
<td>68,363,900,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 23, 2017</td>
<td>4089.01</td>
<td>4255.78</td>
<td>4078.41</td>
<td>4151.52</td>
<td>2,369,820,000</td>
<td>67,553,000,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 22, 2017</td>
<td>3998.35</td>
<td>4128.76</td>
<td>3674.58</td>
<td>4100.52</td>
<td>3,764,240,000</td>
<td>66,051,000,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 21, 2017</td>
<td>4090.48</td>
<td>4109.14</td>
<td>3988.60</td>
<td>4001.74</td>
<td>2,800,890,000</td>
<td>67,567,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 20, 2017</td>
<td>4189.31</td>
<td>4196.29</td>
<td>4069.88</td>
<td>4087.66</td>
<td>2,109,770,000</td>
<td>69,192,700,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 19, 2017</td>
<td>4137.75</td>
<td>4243.26</td>
<td>3970.55</td>
<td>4193.70</td>
<td>2,975,820,000</td>
<td>68,333,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 18, 2017</td>
<td>4324.34</td>
<td>4370.13</td>
<td>4015.40</td>
<td>4160.62</td>
<td>2,941,710,000</td>
<td>71,406,500,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 17, 2017</td>
<td>4384.44</td>
<td>4484.70</td>
<td>4243.71</td>
<td>4331.69</td>
<td>2,553,360,000</td>
<td>72,389,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 16, 2017</td>
<td>4200.34</td>
<td>4381.23</td>
<td>3994.42</td>
<td>4376.63</td>
<td>2,272,040,000</td>
<td>69,342,700,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 15, 2017</td>
<td>4326.99</td>
<td>4455.97</td>
<td>3906.18</td>
<td>4181.93</td>
<td>3,258,050,000</td>
<td>71,425,500,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 14, 2017</td>
<td>4066.10</td>
<td>4325.13</td>
<td>3989.16</td>
<td>4325.13</td>
<td>2,463,090,000</td>
<td>67,112,300,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 13, 2017</td>
<td>3880.04</td>
<td>4208.39</td>
<td>3857.80</td>
<td>4073.26</td>
<td>3,159,090,000</td>
<td>64,034,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 12, 2017</td>
<td>3650.63</td>
<td>3949.92</td>
<td>3613.70</td>
<td>3884.71</td>
<td>2,219,590,000</td>
<td>60,242,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 11, 2017</td>
<td>3373.82</td>
<td>3679.72</td>
<td>3372.12</td>
<td>3650.62</td>
<td>2,021,190,000</td>
<td>55,668,000,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 10, 2017</td>
<td>3341.84</td>
<td>3453.45</td>
<td>3319.47</td>
<td>3381.28</td>
<td>1,515,110,000</td>
<td>55,134,700,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 09, 2017</td>
<td>3420.40</td>
<td>3422.76</td>
<td>3247.67</td>
<td>3342.47</td>
<td>1,468,960,000</td>
<td>56,424,900,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 08, 2017</td>
<td>3370.22</td>
<td>3484.85</td>
<td>3345.83</td>
<td>3419.94</td>
<td>1,752,760,000</td>
<td>55,590,300,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 07, 2017</td>
<td>3212.78</td>
<td>3397.68</td>
<td>3180.89</td>
<td>3378.94</td>
<td>1,482,280,000</td>
<td>52,987,300,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 06, 2017</td>
<td>3257.61</td>
<td>3293.29</td>
<td>3155.60</td>
<td>3213.94</td>
<td>1,105,030,000</td>
<td>53,720,900,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 05, 2017</td>
<td>2897.63</td>
<td>3290.01</td>
<td>2874.83</td>
<td>3252.91</td>
<td>1,945,700,000</td>
<td>47,778,200,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 04, 2017</td>
<td>2806.93</td>
<td>2899.33</td>
<td>2743.72</td>
<td>2895.89</td>
<td>1,002,120,000</td>
<td>46,276,200,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 03, 2017</td>
<td>2709.56</td>
<td>2813.31</td>
<td>2685.14</td>
<td>2804.73</td>
<td>804,797,000</td>
<td>44,666,400,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 02, 2017</td>
<td>2727.13</td>
<td>2762.53</td>
<td>2668.59</td>
<td>2710.67</td>
<td>1,094,950,000</td>
<td>44,950,800,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Aug 01, 2017</td>
<td>2871.30</td>
<td>2921.35</td>
<td>2685.61</td>
<td>2718.26</td>
<td>1,324,670,000</td>
<td>47,321,800,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 31, 2017</td>
<td>2763.24</td>
<td>2889.62</td>
<td>2720.61</td>
<td>2875.34</td>
<td>860,575,000</td>
<td>45,535,800,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 30, 2017</td>
<td>2724.39</td>
<td>2758.53</td>
<td>2644.85</td>
<td>2757.18</td>
<td>705,943,000</td>
<td>44,890,700,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 29, 2017</td>
<td>2807.02</td>
<td>2808.76</td>
<td>2692.80</td>
<td>2726.45</td>
<td>803,746,000</td>
<td>46,246,700,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 28, 2017</td>
<td>2679.73</td>
<td>2897.45</td>
<td>2679.73</td>
<td>2809.01</td>
<td>1,380,100,000</td>
<td>44,144,400,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 27, 2017</td>
<td>2538.71</td>
<td>2693.32</td>
<td>2529.34</td>
<td>2671.78</td>
<td>789,104,000</td>
<td>41,816,500,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 26, 2017</td>
<td>2577.77</td>
<td>2610.76</td>
<td>2450.80</td>
<td>2529.45</td>
<td>937,404,000</td>
<td>42,455,000,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 25, 2017</td>
<td>2757.50</td>
<td>2768.08</td>
<td>2480.96</td>
<td>2576.48</td>
<td>1,460,090,000</td>
<td>45,410,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 24, 2017</td>
<td>2732.70</td>
<td>2777.26</td>
<td>2699.19</td>
<td>2754.86</td>
<td>866,474,000</td>
<td>44,995,600,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 23, 2017</td>
<td>2808.10</td>
<td>2832.18</td>
<td>2653.94</td>
<td>2730.40</td>
<td>1,072,840,000</td>
<td>46,231,100,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 22, 2017</td>
<td>2668.63</td>
<td>2862.42</td>
<td>2657.71</td>
<td>2810.12</td>
<td>1,177,130,000</td>
<td>43,929,600,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 21, 2017</td>
<td>2838.41</td>
<td>2838.41</td>
<td>2621.85</td>
<td>2667.76</td>
<td>1,489,450,000</td>
<td>46,719,000,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 20, 2017</td>
<td>2269.89</td>
<td>2900.70</td>
<td>2269.89</td>
<td>2817.60</td>
<td>2,249,260,000</td>
<td>37,356,800,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 19, 2017</td>
<td>2323.08</td>
<td>2397.17</td>
<td>2260.23</td>
<td>2273.43</td>
<td>1,245,100,000</td>
<td>38,227,800,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 18, 2017</td>
<td>2233.52</td>
<td>2387.61</td>
<td>2164.77</td>
<td>2318.88</td>
<td>1,512,450,000</td>
<td>36,749,400,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 17, 2017</td>
<td>1932.62</td>
<td>2230.49</td>
<td>1932.62</td>
<td>2228.41</td>
<td>1,201,760,000</td>
<td>31,795,000,000</td>
</tr>
<tr class="text-right">
<td class="text-left">Jul 16, 2017</td>
<td>1991.98</td>
<td>2058.77</td>

[<tr class="text-right">
<td class="text-left">Sep 18, 2017</td>
<td>3591.09</td>
<td>4079.23</td>
<td>3591.09</td>
<td>4065.20</td>
<td>1,943,210,000</td>
<td>59,514,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 17, 2017</td>
<td>3606.28</td>
<td>3664.81</td>
<td>3445.64</td>
<td>3582.88</td>
<td>1,239,150,000</td>
<td>59,757,800,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 16, 2017</td>
<td>3637.75</td>
<td>3808.84</td>
<td>3487.79</td>
<td>3625.04</td>
<td>1,818,400,000</td>
<td>60,271,600,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 15, 2017</td>
<td>3166.30</td>
<td>3733.45</td>
<td>2946.62</td>
<td>3637.52</td>
<td>4,148,070,000</td>
<td>52,453,500,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 14, 2017</td>
<td>3875.37</td>
<td>3920.60</td>
<td>3153.86</td>
<td>3154.95</td>
<td>2,716,310,000</td>
<td>64,191,600,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 13, 2017</td>
<td>4131.98</td>
<td>4131.98</td>
<td>3789.92</td>
<td>3882.59</td>
<td>2,219,410,000</td>
<td>68,432,200,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 12, 2017</td>
<td>4168.88</td>
<td>4344.65</td>
<td>4085.22</td>
<td>4130.81</td>
<td>1,864,530,000</td>
<td>69,033,400,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 11, 2017</td>
<td>4122.47</td>
<td>4261.67</td>
<td>4099.40</td>
<td>4161.27</td>
<td>1,557,330,000</td>
<td>68,256,000,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 10, 2017</td>
<td>4229.34</td>
<td>4245.44</td>
<td>3951.04</td>
<td>4122.94</td>
<td>1,679,090,000</td>
<td>70,018,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 09, 2017</td>
<td>4229.81</td>
<td>4308.82</td>
<td>4114.11</td>
<td>4226.06</td>
<td>1,386,230,000</td>
<td>70,017,200,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 08, 2017</td>
<td>4605.16</td>
<td>4661.00</td>
<td>4075.18</td>
<td>4228.75</td>
<td>2,700,890,000</td>
<td>76,220,200,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 07, 2017</td>
<td>4589.14</td>
<td>4655.04</td>
<td>4491.33</td>
<td>4599.88</td>
<td>1,844,620,000</td>
<td>75,945,000,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 06, 2017</td>
<td>4376.59</td>
<td>4617.25</td>
<td>4376.59</td>
<td>4597.12</td>
<td>2,172,100,000</td>
<td>72,418,700,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 05, 2017</td>
<td>4228.29</td>
<td>4427.84</td>
<td>3998.11</td>
<td>4376.53</td>
<td>2,697,970,000</td>
<td>69,954,400,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 04, 2017</td>
<td>4591.63</td>
<td>4591.63</td>
<td>4108.40</td>
<td>4236.31</td>
<td>2,987,330,000</td>
<td>75,955,500,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 03, 2017</td>
<td>4585.27</td>
<td>4714.08</td>
<td>4417.59</td>
<td>4582.96</td>
<td>1,933,190,000</td>
<td>75,841,700,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 02, 2017</td>
<td>4901.42</td>
<td>4975.04</td>
<td>4469.24</td>
<td>4578.77</td>
<td>2,722,140,000</td>
<td>81,060,600,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Sep 01, 2017</td>
<td>4701.76</td>
<td>4892.01</td>
<td>4678.53</td>
<td>4892.01</td>
<td>2,599,080,000</td>
<td>77,748,400,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 31, 2017</td>
<td>4555.59</td>
<td>4736.05</td>
<td>4549.40</td>
<td>4703.39</td>
<td>1,944,930,000</td>
<td>75,322,300,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 30, 2017</td>
<td>4570.36</td>
<td>4626.52</td>
<td>4471.41</td>
<td>4565.30</td>
<td>1,937,850,000</td>
<td>75,556,600,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 29, 2017</td>
<td>4389.21</td>
<td>4625.68</td>
<td>4352.13</td>
<td>4579.02</td>
<td>2,486,080,000</td>
<td>72,553,800,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 28, 2017</td>
<td>4384.45</td>
<td>4403.93</td>
<td>4224.64</td>
<td>4382.66</td>
<td>1,959,330,000</td>
<td>72,467,900,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 27, 2017</td>
<td>4345.10</td>
<td>4416.59</td>
<td>4317.29</td>
<td>4382.88</td>
<td>1,537,460,000</td>
<td>71,809,200,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 26, 2017</td>
<td>4372.06</td>
<td>4379.28</td>
<td>4269.52</td>
<td>4352.40</td>
<td>1,511,610,000</td>
<td>72,249,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 25, 2017</td>
<td>4332.82</td>
<td>4455.70</td>
<td>4307.35</td>
<td>4371.60</td>
<td>1,727,970,000</td>
<td>71,595,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 24, 2017</td>
<td>4137.60</td>
<td>4376.39</td>
<td>4130.26</td>
<td>4334.68</td>
<td>2,037,750,000</td>
<td>68,363,900,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 23, 2017</td>
<td>4089.01</td>
<td>4255.78</td>
<td>4078.41</td>
<td>4151.52</td>
<td>2,369,820,000</td>
<td>67,553,000,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 22, 2017</td>
<td>3998.35</td>
<td>4128.76</td>
<td>3674.58</td>
<td>4100.52</td>
<td>3,764,240,000</td>
<td>66,051,000,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 21, 2017</td>
<td>4090.48</td>
<td>4109.14</td>
<td>3988.60</td>
<td>4001.74</td>
<td>2,800,890,000</td>
<td>67,567,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 20, 2017</td>
<td>4189.31</td>
<td>4196.29</td>
<td>4069.88</td>
<td>4087.66</td>
<td>2,109,770,000</td>
<td>69,192,700,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 19, 2017</td>
<td>4137.75</td>
<td>4243.26</td>
<td>3970.55</td>
<td>4193.70</td>
<td>2,975,820,000</td>
<td>68,333,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 18, 2017</td>
<td>4324.34</td>
<td>4370.13</td>
<td>4015.40</td>
<td>4160.62</td>
<td>2,941,710,000</td>
<td>71,406,500,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 17, 2017</td>
<td>4384.44</td>
<td>4484.70</td>
<td>4243.71</td>
<td>4331.69</td>
<td>2,553,360,000</td>
<td>72,389,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 16, 2017</td>
<td>4200.34</td>
<td>4381.23</td>
<td>3994.42</td>
<td>4376.63</td>
<td>2,272,040,000</td>
<td>69,342,700,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 15, 2017</td>
<td>4326.99</td>
<td>4455.97</td>
<td>3906.18</td>
<td>4181.93</td>
<td>3,258,050,000</td>
<td>71,425,500,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 14, 2017</td>
<td>4066.10</td>
<td>4325.13</td>
<td>3989.16</td>
<td>4325.13</td>
<td>2,463,090,000</td>
<td>67,112,300,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 13, 2017</td>
<td>3880.04</td>
<td>4208.39</td>
<td>3857.80</td>
<td>4073.26</td>
<td>3,159,090,000</td>
<td>64,034,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 12, 2017</td>
<td>3650.63</td>
<td>3949.92</td>
<td>3613.70</td>
<td>3884.71</td>
<td>2,219,590,000</td>
<td>60,242,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 11, 2017</td>
<td>3373.82</td>
<td>3679.72</td>
<td>3372.12</td>
<td>3650.62</td>
<td>2,021,190,000</td>
<td>55,668,000,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 10, 2017</td>
<td>3341.84</td>
<td>3453.45</td>
<td>3319.47</td>
<td>3381.28</td>
<td>1,515,110,000</td>
<td>55,134,700,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 09, 2017</td>
<td>3420.40</td>
<td>3422.76</td>
<td>3247.67</td>
<td>3342.47</td>
<td>1,468,960,000</td>
<td>56,424,900,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 08, 2017</td>
<td>3370.22</td>
<td>3484.85</td>
<td>3345.83</td>
<td>3419.94</td>
<td>1,752,760,000</td>
<td>55,590,300,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 07, 2017</td>
<td>3212.78</td>
<td>3397.68</td>
<td>3180.89</td>
<td>3378.94</td>
<td>1,482,280,000</td>
<td>52,987,300,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 06, 2017</td>
<td>3257.61</td>
<td>3293.29</td>
<td>3155.60</td>
<td>3213.94</td>
<td>1,105,030,000</td>
<td>53,720,900,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 05, 2017</td>
<td>2897.63</td>
<td>3290.01</td>
<td>2874.83</td>
<td>3252.91</td>
<td>1,945,700,000</td>
<td>47,778,200,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 04, 2017</td>
<td>2806.93</td>
<td>2899.33</td>
<td>2743.72</td>
<td>2895.89</td>
<td>1,002,120,000</td>
<td>46,276,200,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 03, 2017</td>
<td>2709.56</td>
<td>2813.31</td>
<td>2685.14</td>
<td>2804.73</td>
<td>804,797,000</td>
<td>44,666,400,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 02, 2017</td>
<td>2727.13</td>
<td>2762.53</td>
<td>2668.59</td>
<td>2710.67</td>
<td>1,094,950,000</td>
<td>44,950,800,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Aug 01, 2017</td>
<td>2871.30</td>
<td>2921.35</td>
<td>2685.61</td>
<td>2718.26</td>
<td>1,324,670,000</td>
<td>47,321,800,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 31, 2017</td>
<td>2763.24</td>
<td>2889.62</td>
<td>2720.61</td>
<td>2875.34</td>
<td>860,575,000</td>
<td>45,535,800,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 30, 2017</td>
<td>2724.39</td>
<td>2758.53</td>
<td>2644.85</td>
<td>2757.18</td>
<td>705,943,000</td>
<td>44,890,700,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 29, 2017</td>
<td>2807.02</td>
<td>2808.76</td>
<td>2692.80</td>
<td>2726.45</td>
<td>803,746,000</td>
<td>46,246,700,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 28, 2017</td>
<td>2679.73</td>
<td>2897.45</td>
<td>2679.73</td>
<td>2809.01</td>
<td>1,380,100,000</td>
<td>44,144,400,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 27, 2017</td>
<td>2538.71</td>
<td>2693.32</td>
<td>2529.34</td>
<td>2671.78</td>
<td>789,104,000</td>
<td>41,816,500,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 26, 2017</td>
<td>2577.77</td>
<td>2610.76</td>
<td>2450.80</td>
<td>2529.45</td>
<td>937,404,000</td>
<td>42,455,000,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 25, 2017</td>
<td>2757.50</td>
<td>2768.08</td>
<td>2480.96</td>
<td>2576.48</td>
<td>1,460,090,000</td>
<td>45,410,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 24, 2017</td>
<td>2732.70</td>
<td>2777.26</td>
<td>2699.19</td>
<td>2754.86</td>
<td>866,474,000</td>
<td>44,995,600,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 23, 2017</td>
<td>2808.10</td>
<td>2832.18</td>
<td>2653.94</td>
<td>2730.40</td>
<td>1,072,840,000</td>
<td>46,231,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 22, 2017</td>
<td>2668.63</td>
<td>2862.42</td>
<td>2657.71</td>
<td>2810.12</td>
<td>1,177,130,000</td>
<td>43,929,600,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 21, 2017</td>
<td>2838.41</td>
<td>2838.41</td>
<td>2621.85</td>
<td>2667.76</td>
<td>1,489,450,000</td>
<td>46,719,000,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 20, 2017</td>
<td>2269.89</td>
<td>2900.70</td>
<td>2269.89</td>
<td>2817.60</td>
<td>2,249,260,000</td>
<td>37,356,800,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 19, 2017</td>
<td>2323.08</td>
<td>2397.17</td>
<td>2260.23</td>
<td>2273.43</td>
<td>1,245,100,000</td>
<td>38,227,800,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 18, 2017</td>
<td>2233.52</td>
<td>2387.61</td>
<td>2164.77</td>
<td>2318.88</td>
<td>1,512,450,000</td>
<td>36,749,400,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 17, 2017</td>
<td>1932.62</td>
<td>2230.49</td>
<td>1932.62</td>
<td>2228.41</td>
<td>1,201,760,000</td>
<td>31,795,000,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 16, 2017</td>
<td>1991.98</td>
<td>2058.77</td>
<td>1843.03</td>
<td>1929.82</td>
<td>1,182,870,000</td>
<td>32,767,600,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 15, 2017</td>
<td>2230.12</td>
<td>2231.14</td>
<td>1990.41</td>
<td>1998.86</td>
<td>993,608,000</td>
<td>36,681,300,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 14, 2017</td>
<td>2360.59</td>
<td>2363.25</td>
<td>2183.22</td>
<td>2233.34</td>
<td>882,503,000</td>
<td>38,823,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 13, 2017</td>
<td>2402.70</td>
<td>2425.22</td>
<td>2340.83</td>
<td>2357.90</td>
<td>835,770,000</td>
<td>39,511,000,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 12, 2017</td>
<td>2332.77</td>
<td>2423.71</td>
<td>2275.14</td>
<td>2398.84</td>
<td>1,117,410,000</td>
<td>38,355,900,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 11, 2017</td>
<td>2385.89</td>
<td>2413.47</td>
<td>2296.81</td>
<td>2337.79</td>
<td>1,329,760,000</td>
<td>39,224,200,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 10, 2017</td>
<td>2525.25</td>
<td>2537.16</td>
<td>2321.13</td>
<td>2372.56</td>
<td>1,111,200,000</td>
<td>41,509,000,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 09, 2017</td>
<td>2572.61</td>
<td>2635.49</td>
<td>2517.59</td>
<td>2518.44</td>
<td>527,856,000</td>
<td>42,283,200,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 08, 2017</td>
<td>2520.27</td>
<td>2571.34</td>
<td>2492.31</td>
<td>2571.34</td>
<td>733,330,000</td>
<td>41,417,700,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 07, 2017</td>
<td>2608.59</td>
<td>2916.14</td>
<td>2498.87</td>
<td>2518.66</td>
<td>917,412,000</td>
<td>42,864,200,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 06, 2017</td>
<td>2608.10</td>
<td>2616.72</td>
<td>2581.69</td>
<td>2608.56</td>
<td>761,957,000</td>
<td>42,851,400,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 05, 2017</td>
<td>2602.87</td>
<td>2622.65</td>
<td>2538.55</td>
<td>2601.99</td>
<td>941,566,000</td>
<td>42,760,800,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 04, 2017</td>
<td>2561.00</td>
<td>2631.59</td>
<td>2559.35</td>
<td>2601.64</td>
<td>985,516,000</td>
<td>42,067,900,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 03, 2017</td>
<td>2498.56</td>
<td>2595.00</td>
<td>2480.47</td>
<td>2564.06</td>
<td>964,112,000</td>
<td>41,037,200,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 02, 2017</td>
<td>2436.40</td>
<td>2514.28</td>
<td>2394.84</td>
<td>2506.47</td>
<td>803,747,000</td>
<td>40,010,500,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jul 01, 2017</td>
<td>2492.60</td>
<td>2515.27</td>
<td>2419.23</td>
<td>2434.55</td>
<td>779,914,000</td>
<td>40,928,200,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 30, 2017</td>
<td>2539.24</td>
<td>2559.25</td>
<td>2478.43</td>
<td>2480.84</td>
<td>860,273,000</td>
<td>41,689,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 29, 2017</td>
<td>2567.56</td>
<td>2588.83</td>
<td>2510.48</td>
<td>2539.32</td>
<td>949,979,000</td>
<td>42,150,300,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 28, 2017</td>
<td>2553.03</td>
<td>2603.98</td>
<td>2484.42</td>
<td>2574.79</td>
<td>1,183,870,000</td>
<td>41,906,700,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 27, 2017</td>
<td>2478.45</td>
<td>2552.45</td>
<td>2332.99</td>
<td>2552.45</td>
<td>1,489,790,000</td>
<td>40,677,900,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 26, 2017</td>
<td>2590.57</td>
<td>2615.25</td>
<td>2376.29</td>
<td>2478.45</td>
<td>1,663,280,000</td>
<td>42,514,000,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 25, 2017</td>
<td>2607.25</td>
<td>2682.26</td>
<td>2552.12</td>
<td>2589.41</td>
<td>1,161,100,000</td>
<td>42,783,800,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 24, 2017</td>
<td>2738.52</td>
<td>2757.94</td>
<td>2583.19</td>
<td>2608.72</td>
<td>982,750,000</td>
<td>44,932,900,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 23, 2017</td>
<td>2707.34</td>
<td>2765.17</td>
<td>2706.37</td>
<td>2744.91</td>
<td>961,319,000</td>
<td>44,415,900,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 22, 2017</td>
<td>2691.03</td>
<td>2723.74</td>
<td>2642.36</td>
<td>2705.41</td>
<td>1,097,940,000</td>
<td>44,143,700,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 21, 2017</td>
<td>2709.43</td>
<td>2772.01</td>
<td>2660.40</td>
<td>2689.10</td>
<td>1,626,580,000</td>
<td>44,440,800,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 20, 2017</td>
<td>2591.26</td>
<td>2763.45</td>
<td>2589.82</td>
<td>2721.79</td>
<td>1,854,190,000</td>
<td>42,498,000,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 19, 2017</td>
<td>2549.03</td>
<td>2662.85</td>
<td>2549.03</td>
<td>2589.60</td>
<td>1,446,840,000</td>
<td>41,800,600,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 18, 2017</td>
<td>2655.35</td>
<td>2662.10</td>
<td>2516.33</td>
<td>2548.29</td>
<td>1,178,660,000</td>
<td>43,539,300,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 17, 2017</td>
<td>2514.01</td>
<td>2685.19</td>
<td>2484.96</td>
<td>2655.88</td>
<td>1,534,510,000</td>
<td>41,217,200,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 16, 2017</td>
<td>2469.57</td>
<td>2539.92</td>
<td>2385.15</td>
<td>2518.56</td>
<td>1,195,190,000</td>
<td>40,484,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 15, 2017</td>
<td>2499.58</td>
<td>2534.71</td>
<td>2212.96</td>
<td>2464.58</td>
<td>2,026,260,000</td>
<td>40,971,300,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 14, 2017</td>
<td>2716.88</td>
<td>2786.83</td>
<td>2412.94</td>
<td>2506.37</td>
<td>1,696,560,000</td>
<td>44,528,300,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 13, 2017</td>
<td>2680.91</td>
<td>2789.04</td>
<td>2650.38</td>
<td>2717.02</td>
<td>1,781,200,000</td>
<td>43,934,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 12, 2017</td>
<td>2953.22</td>
<td>2997.26</td>
<td>2518.56</td>
<td>2659.63</td>
<td>2,569,530,000</td>
<td>48,391,200,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 11, 2017</td>
<td>2942.41</td>
<td>2996.60</td>
<td>2840.53</td>
<td>2958.11</td>
<td>1,752,400,000</td>
<td>48,208,700,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 10, 2017</td>
<td>2828.14</td>
<td>2950.99</td>
<td>2746.55</td>
<td>2947.71</td>
<td>2,018,890,000</td>
<td>46,331,400,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 09, 2017</td>
<td>2807.44</td>
<td>2901.71</td>
<td>2795.62</td>
<td>2823.81</td>
<td>1,348,950,000</td>
<td>45,987,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 08, 2017</td>
<td>2720.49</td>
<td>2815.30</td>
<td>2670.95</td>
<td>2805.62</td>
<td>1,281,170,000</td>
<td>44,557,100,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 07, 2017</td>
<td>2869.38</td>
<td>2869.38</td>
<td>2700.56</td>
<td>2732.16</td>
<td>1,517,710,000</td>
<td>46,989,800,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 06, 2017</td>
<td>2690.84</td>
<td>2999.91</td>
<td>2690.84</td>
<td>2863.20</td>
<td>2,089,610,000</td>
<td>44,061,000,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 05, 2017</td>
<td>2512.40</td>
<td>2686.81</td>
<td>2510.22</td>
<td>2686.81</td>
<td>1,369,310,000</td>
<td>41,133,900,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 04, 2017</td>
<td>2547.79</td>
<td>2585.89</td>
<td>2452.54</td>
<td>2511.81</td>
<td>1,355,120,000</td>
<td>41,708,200,000</td>
</tr>, <tr class="text-right">
<td class="text-left">Jun 03, 2017</td>
<td>2493.72</td>
<td>2581.91</td>
<td>2423.57</td>
<td>2515.35</td>

<tr class="text-right">
<td class="text-left">Sep 18, 2017</td>
<td>3591.09</td>
<td>4079.23</td>
<td>3591.09</td>
<td>4065.20</td>
<td>1,943,210,000</td>
<td>59,514,100,000</td>
</tr>

[<td class="text-left">Sep 18, 2017</td>, <td>3591.09</td>, <td>4079.23</td>, <td>3591.09</td>, <td>4065.20</td>, <td>1,943,210,000</td>, <td>59,514,100,000</td>]

In [82]:
print(divclass4[0])
print("")
print(divclass4[1])
print("")
print(divclass4[2])
print("")
print(divclass4[3])
print("")
print(divclass4[4])
print("")
print(divclass4[5])
print("")
print(divclass4[6])

<td class="text-left">Sep 18, 2017</td>

<td>3591.09</td>

<td>4079.23</td>

<td>3591.09</td>

<td>4065.20</td>

<td>1,943,210,000</td>

<td>59,514,100,000</td>

In [90]:
# I don't like the fact that the <td> and </td> is showing up . Get that out . 
start_normal = '<td>'
start_fordate = '<td class="text-left">'
end = '</td>'
s1=str(divclass4[0])
s2=str(divclass4[1])
s3=str(divclass4[2])
s4=str(divclass4[3])
s5=str(divclass4[4])
s6=str(divclass4[5])
s7=str(divclass4[6])

print (s1[s1.find(start_fordate)+len(start_fordate):s1.rfind(end)])
print("")
print (s2[s2.find(start_normal)+len(start_normal):s2.rfind(end)])
print("")
print (s3[s3.find(start_normal)+len(start_normal):s3.rfind(end)])
print("")
print (s4[s4.find(start_normal)+len(start_normal):s4.rfind(end)])
print("")
print (s5[s5.find(start_normal)+len(start_normal):s5.rfind(end)])
print("")
print (s6[s6.find(start_normal)+len(start_normal):s6.rfind(end)])
print("")
print (s7[s7.find(start_normal)+len(start_normal):s7.rfind(end)])

Sep 18, 2017

3591.09

4079.23

3591.09

4065.20

1,943,210,000

59,514,100,000

In [89]:
# now , let us see how we can extend this process for all the dates for which data is available 
# first , let us see how many dates we have with us 
print (len(divclass2))
# let us verify this . We have data from sept 18 2017 to april 28 2013 . 
# a quick look through http://www.thecalculatorsite.com/misc/days-between-dates.php verifies that it is right . 
# cool

1605

In [102]:
# let us see if we can get all the possible dates for bitcoin 
dic1=[]
for x in range(0,len(divclass2)):
    divclass4=divclass2[x].find_all("td")
    s1=str(divclass4[0])
    print (s1[s1.find(start_fordate)+len(start_fordate):s1.rfind(end)])
    # cool 
    # we apply the same logic for any other element in here . ( look at ln90 for what I mean)

Sep 18, 2017
Sep 17, 2017
Sep 16, 2017
Sep 15, 2017
Sep 14, 2017
Sep 13, 2017
Sep 12, 2017
Sep 11, 2017
Sep 10, 2017
Sep 09, 2017
Sep 08, 2017
Sep 07, 2017
Sep 06, 2017
Sep 05, 2017
Sep 04, 2017
Sep 03, 2017
Sep 02, 2017
Sep 01, 2017
Aug 31, 2017
Aug 30, 2017
Aug 29, 2017
Aug 28, 2017
Aug 27, 2017
Aug 26, 2017
Aug 25, 2017
Aug 24, 2017
Aug 23, 2017
Aug 22, 2017
Aug 21, 2017
Aug 20, 2017
Aug 19, 2017
Aug 18, 2017
Aug 17, 2017
Aug 16, 2017
Aug 15, 2017
Aug 14, 2017
Aug 13, 2017
Aug 12, 2017
Aug 11, 2017
Aug 10, 2017
Aug 09, 2017
Aug 08, 2017
Aug 07, 2017
Aug 06, 2017
Aug 05, 2017
Aug 04, 2017
Aug 03, 2017
Aug 02, 2017
Aug 01, 2017
Jul 31, 2017
Jul 30, 2017
Jul 29, 2017
Jul 28, 2017
Jul 27, 2017
Jul 26, 2017
Jul 25, 2017
Jul 24, 2017
Jul 23, 2017
Jul 22, 2017
Jul 21, 2017
Jul 20, 2017
Jul 19, 2017
Jul 18, 2017
Jul 17, 2017
Jul 16, 2017
Jul 15, 2017
Jul 14, 2017
Jul 13, 2017
Jul 12, 2017
Jul 11, 2017
Jul 10, 2017
Jul 09, 2017
Jul 08, 2017
Jul 07, 2017
Jul 06, 2017
Jul 05, 2017
Jul 04, 2017
Jul 03, 2017
Jul 02, 2017
Jul 01, 2017
Jun 30, 2017
Jun 29, 2017
Jun 28, 2017
Jun 27, 2017
Jun 26, 2017
Jun 25, 2017
Jun 24, 2017
Jun 23, 2017
Jun 22, 2017
Jun 21, 2017
Jun 20, 2017
Jun 19, 2017
Jun 18, 2017
Jun 17, 2017
Jun 16, 2017
Jun 15, 2017
Jun 14, 2017
Jun 13, 2017
Jun 12, 2017
Jun 11, 2017
Jun 10, 2017
Jun 09, 2017
Jun 08, 2017
Jun 07, 2017
Jun 06, 2017
Jun 05, 2017
Jun 04, 2017
Jun 03, 2017
Jun 02, 2017
Jun 01, 2017
May 31, 2017
May 30, 2017
May 29, 2017
May 28, 2017
May 27, 2017
May 26, 2017
May 25, 2017
May 24, 2017
May 23, 2017
May 22, 2017
May 21, 2017
May 20, 2017
May 19, 2017
May 18, 2017
May 17, 2017
May 16, 2017
May 15, 2017
May 14, 2017
May 13, 2017
May 12, 2017
May 11, 2017
May 10, 2017
May 09, 2017
May 08, 2017
May 07, 2017
May 06, 2017
May 05, 2017
May 04, 2017
May 03, 2017
May 02, 2017
May 01, 2017
Apr 30, 2017
Apr 29, 2017
Apr 28, 2017
Apr 27, 2017
Apr 26, 2017
Apr 25, 2017
Apr 24, 2017
Apr 23, 2017
Apr 22, 2017
Apr 21, 2017
Apr 20, 2017
Apr 19, 2017
Apr 18, 2017
Apr 17, 2017
Apr 16, 2017
Apr 15, 2017
Apr 14, 2017
Apr 13, 2017
Apr 12, 2017
Apr 11, 2017
Apr 10, 2017
Apr 09, 2017
Apr 08, 2017
Apr 07, 2017
Apr 06, 2017
Apr 05, 2017
Apr 04, 2017
Apr 03, 2017
Apr 02, 2017
Apr 01, 2017
Mar 31, 2017
Mar 30, 2017
Mar 29, 2017
Mar 28, 2017
Mar 27, 2017
Mar 26, 2017
Mar 25, 2017
Mar 24, 2017
Mar 23, 2017
Mar 22, 2017
Mar 21, 2017
Mar 20, 2017
Mar 19, 2017
Mar 18, 2017
Mar 17, 2017
Mar 16, 2017
Mar 15, 2017
Mar 14, 2017
Mar 13, 2017
Mar 12, 2017
Mar 11, 2017
Mar 10, 2017
Mar 09, 2017
Mar 08, 2017
Mar 07, 2017
Mar 06, 2017
Mar 05, 2017
Mar 04, 2017
Mar 03, 2017
Mar 02, 2017
Mar 01, 2017
Feb 28, 2017
Feb 27, 2017
Feb 26, 2017
Feb 25, 2017
Feb 24, 2017
Feb 23, 2017
Feb 22, 2017
Feb 21, 2017
Feb 20, 2017
Feb 19, 2017
Feb 18, 2017
Feb 17, 2017
Feb 16, 2017
Feb 15, 2017
Feb 14, 2017
Feb 13, 2017
Feb 12, 2017
Feb 11, 2017
Feb 10, 2017
Feb 09, 2017
Feb 08, 2017
Feb 07, 2017
Feb 06, 2017
Feb 05, 2017
Feb 04, 2017
Feb 03, 2017
Feb 02, 2017
Feb 01, 2017
Jan 31, 2017
Jan 30, 2017
Jan 29, 2017
Jan 28, 2017
Jan 27, 2017
Jan 26, 2017
Jan 25, 2017
Jan 24, 2017
Jan 23, 2017
Jan 22, 2017
Jan 21, 2017
Jan 20, 2017
Jan 19, 2017
Jan 18, 2017
Jan 17, 2017
Jan 16, 2017
Jan 15, 2017
Jan 14, 2017
Jan 13, 2017
Jan 12, 2017
Jan 11, 2017
Jan 10, 2017
Jan 09, 2017
Jan 08, 2017
Jan 07, 2017
Jan 06, 2017
Jan 05, 2017
Jan 04, 2017
Jan 03, 2017
Jan 02, 2017
Jan 01, 2017
Dec 31, 2016
Dec 30, 2016
Dec 29, 2016
Dec 28, 2016
Dec 27, 2016
Dec 26, 2016
Dec 25, 2016
Dec 24, 2016
Dec 23, 2016
Dec 22, 2016
Dec 21, 2016
Dec 20, 2016
Dec 19, 2016
Dec 18, 2016
Dec 17, 2016
Dec 16, 2016
Dec 15, 2016
Dec 14, 2016
Dec 13, 2016
Dec 12, 2016
Dec 11, 2016
Dec 10, 2016
Dec 09, 2016
Dec 08, 2016
Dec 07, 2016
Dec 06, 2016
Dec 05, 2016
Dec 04, 2016
Dec 03, 2016
Dec 02, 2016
Dec 01, 2016
Nov 30, 2016
Nov 29, 2016
Nov 28, 2016
Nov 27, 2016
Nov 26, 2016
Nov 25, 2016
Nov 24, 2016
Nov 23, 2016
Nov 22, 2016
Nov 21, 2016
Nov 20, 2016
Nov 19, 2016
Nov 18, 2016
Nov 17, 2016
Nov 16, 2016
Nov 15, 2016
Nov 14, 2016
Nov 13, 2016
Nov 12, 2016
Nov 11, 2016
Nov 10, 2016
Nov 09, 2016
Nov 08, 2016
Nov 07, 2016
Nov 06, 2016
Nov 05, 2016
Nov 04, 2016
Nov 03, 2016
Nov 02, 2016
Nov 01, 2016
Oct 31, 2016
Oct 30, 2016
Oct 29, 2016
Oct 28, 2016
Oct 27, 2016
Oct 26, 2016
Oct 25, 2016
Oct 24, 2016
Oct 23, 2016
Oct 22, 2016
Oct 21, 2016
Oct 20, 2016
Oct 19, 2016
Oct 18, 2016
Oct 17, 2016
Oct 16, 2016
Oct 15, 2016
Oct 14, 2016
Oct 13, 2016
Oct 12, 2016
Oct 11, 2016
Oct 10, 2016
Oct 09, 2016
Oct 08, 2016
Oct 07, 2016
Oct 06, 2016
Oct 05, 2016
Oct 04, 2016
Oct 03, 2016
Oct 02, 2016
Oct 01, 2016
Sep 30, 2016
Sep 29, 2016
Sep 28, 2016
Sep 27, 2016
Sep 26, 2016
Sep 25, 2016
Sep 24, 2016
Sep 23, 2016
Sep 22, 2016
Sep 21, 2016
Sep 20, 2016
Sep 19, 2016
Sep 18, 2016
Sep 17, 2016
Sep 16, 2016
Sep 15, 2016
Sep 14, 2016
Sep 13, 2016
Sep 12, 2016
Sep 11, 2016
Sep 10, 2016
Sep 09, 2016
Sep 08, 2016
Sep 07, 2016
Sep 06, 2016
Sep 05, 2016
Sep 04, 2016
Sep 03, 2016
Sep 02, 2016
Sep 01, 2016
Aug 31, 2016
Aug 30, 2016
Aug 29, 2016
Aug 28, 2016
Aug 27, 2016
Aug 26, 2016
Aug 25, 2016
Aug 24, 2016
Aug 23, 2016
Aug 22, 2016
Aug 21, 2016
Aug 20, 2016
Aug 19, 2016
Aug 18, 2016
Aug 17, 2016
Aug 16, 2016
Aug 15, 2016
Aug 14, 2016
Aug 13, 2016
Aug 12, 2016
Aug 11, 2016
Aug 10, 2016
Aug 09, 2016
Aug 08, 2016
Aug 07, 2016
Aug 06, 2016
Aug 05, 2016
Aug 04, 2016
Aug 03, 2016
Aug 02, 2016
Aug 01, 2016
Jul 31, 2016
Jul 30, 2016
Jul 29, 2016
Jul 28, 2016
Jul 27, 2016
Jul 26, 2016
Jul 25, 2016
Jul 24, 2016
Jul 23, 2016
Jul 22, 2016
Jul 21, 2016
Jul 20, 2016
Jul 19, 2016
Jul 18, 2016
Jul 17, 2016
Jul 16, 2016
Jul 15, 2016
Jul 14, 2016
Jul 13, 2016
Jul 12, 2016
Jul 11, 2016
Jul 10, 2016
Jul 09, 2016
Jul 08, 2016
Jul 07, 2016
Jul 06, 2016
Jul 05, 2016
Jul 04, 2016
Jul 03, 2016
Jul 02, 2016
Jul 01, 2016
Jun 30, 2016
Jun 29, 2016
Jun 28, 2016
Jun 27, 2016
Jun 26, 2016
Jun 25, 2016
Jun 24, 2016
Jun 23, 2016
Jun 22, 2016
Jun 21, 2016
Jun 20, 2016
Jun 19, 2016
Jun 18, 2016
Jun 17, 2016
Jun 16, 2016
Jun 15, 2016
Jun 14, 2016
Jun 13, 2016
Jun 12, 2016
Jun 11, 2016
Jun 10, 2016
Jun 09, 2016
Jun 08, 2016
Jun 07, 2016
Jun 06, 2016
Jun 05, 2016
Jun 04, 2016
Jun 03, 2016
Jun 02, 2016
Jun 01, 2016
May 31, 2016
May 30, 2016
May 29, 2016
May 28, 2016
May 27, 2016
May 26, 2016
May 25, 2016
May 24, 2016
May 23, 2016
May 22, 2016
May 21, 2016
May 20, 2016
May 19, 2016
May 18, 2016
May 17, 2016
May 16, 2016
May 15, 2016
May 14, 2016
May 13, 2016
May 12, 2016
May 11, 2016
May 10, 2016
May 09, 2016
May 08, 2016
May 07, 2016
May 06, 2016
May 05, 2016
May 04, 2016
May 03, 2016
May 02, 2016
May 01, 2016
Apr 30, 2016
Apr 29, 2016
Apr 28, 2016
Apr 27, 2016
Apr 26, 2016
Apr 25, 2016
Apr 24, 2016
Apr 23, 2016
Apr 22, 2016
Apr 21, 2016
Apr 20, 2016
Apr 19, 2016
Apr 18, 2016
Apr 17, 2016
Apr 16, 2016
Apr 15, 2016
Apr 14, 2016
Apr 13, 2016
Apr 12, 2016
Apr 11, 2016
Apr 10, 2016
Apr 09, 2016
Apr 08, 2016
Apr 07, 2016
Apr 06, 2016
Apr 05, 2016
Apr 04, 2016
Apr 03, 2016
Apr 02, 2016
Apr 01, 2016
Mar 31, 2016
Mar 30, 2016
Mar 29, 2016
Mar 28, 2016
Mar 27, 2016
Mar 26, 2016
Mar 25, 2016
Mar 24, 2016
Mar 23, 2016
Mar 22, 2016
Mar 21, 2016
Mar 20, 2016
Mar 19, 2016
Mar 18, 2016
Mar 17, 2016
Mar 16, 2016
Mar 15, 2016
Mar 14, 2016
Mar 13, 2016
Mar 12, 2016
Mar 11, 2016
Mar 10, 2016
Mar 09, 2016
Mar 08, 2016
Mar 07, 2016
Mar 06, 2016
Mar 05, 2016
Mar 04, 2016
Mar 03, 2016
Mar 02, 2016
Mar 01, 2016
Feb 29, 2016
Feb 28, 2016
Feb 27, 2016
Feb 26, 2016
Feb 25, 2016
Feb 24, 2016
Feb 23, 2016
Feb 22, 2016
Feb 21, 2016
Feb 20, 2016
Feb 19, 2016
Feb 18, 2016
Feb 17, 2016
Feb 16, 2016
Feb 15, 2016
Feb 14, 2016
Feb 13, 2016
Feb 12, 2016
Feb 11, 2016
Feb 10, 2016
Feb 09, 2016
Feb 08, 2016
Feb 07, 2016
Feb 06, 2016
Feb 05, 2016
Feb 04, 2016
Feb 03, 2016
Feb 02, 2016
Feb 01, 2016
Jan 31, 2016
Jan 30, 2016
Jan 29, 2016
Jan 28, 2016
Jan 27, 2016
Jan 26, 2016
Jan 25, 2016
Jan 24, 2016
Jan 23, 2016
Jan 22, 2016
Jan 21, 2016
Jan 20, 2016
Jan 19, 2016
Jan 18, 2016
Jan 17, 2016
Jan 16, 2016
Jan 15, 2016
Jan 14, 2016
Jan 13, 2016
Jan 12, 2016
Jan 11, 2016
Jan 10, 2016
Jan 09, 2016
Jan 08, 2016
Jan 07, 2016
Jan 06, 2016
Jan 05, 2016
Jan 04, 2016
Jan 03, 2016
Jan 02, 2016
Jan 01, 2016
Dec 31, 2015
Dec 30, 2015
Dec 29, 2015
Dec 28, 2015
Dec 27, 2015
Dec 26, 2015
Dec 25, 2015
Dec 24, 2015
Dec 23, 2015
Dec 22, 2015
Dec 21, 2015
Dec 20, 2015
Dec 19, 2015
Dec 18, 2015
Dec 17, 2015
Dec 16, 2015
Dec 15, 2015
Dec 14, 2015
Dec 13, 2015
Dec 12, 2015
Dec 11, 2015
Dec 10, 2015
Dec 09, 2015
Dec 08, 2015
Dec 07, 2015
Dec 06, 2015
Dec 05, 2015
Dec 04, 2015
Dec 03, 2015
Dec 02, 2015
Dec 01, 2015
Nov 30, 2015
Nov 29, 2015
Nov 28, 2015
Nov 27, 2015
Nov 26, 2015
Nov 25, 2015
Nov 24, 2015
Nov 23, 2015
Nov 22, 2015
Nov 21, 2015
Nov 20, 2015
Nov 19, 2015
Nov 18, 2015
Nov 17, 2015
Nov 16, 2015
Nov 15, 2015
Nov 14, 2015
Nov 13, 2015
Nov 12, 2015
Nov 11, 2015
Nov 10, 2015
Nov 09, 2015
Nov 08, 2015
Nov 07, 2015
Nov 06, 2015
Nov 05, 2015
Nov 04, 2015
Nov 03, 2015
Nov 02, 2015
Nov 01, 2015
Oct 31, 2015
Oct 30, 2015
Oct 29, 2015
Oct 28, 2015
Oct 27, 2015
Oct 26, 2015
Oct 25, 2015
Oct 24, 2015
Oct 23, 2015
Oct 22, 2015
Oct 21, 2015
Oct 20, 2015
Oct 19, 2015
Oct 18, 2015
Oct 17, 2015
Oct 16, 2015
Oct 15, 2015
Oct 14, 2015
Oct 13, 2015
Oct 12, 2015
Oct 11, 2015
Oct 10, 2015
Oct 09, 2015
Oct 08, 2015
Oct 07, 2015
Oct 06, 2015
Oct 05, 2015
Oct 04, 2015
Oct 03, 2015
Oct 02, 2015
Oct 01, 2015
Sep 30, 2015
Sep 29, 2015
Sep 28, 2015
Sep 27, 2015
Sep 26, 2015
Sep 25, 2015
Sep 24, 2015
Sep 23, 2015
Sep 22, 2015
Sep 21, 2015
Sep 20, 2015
Sep 19, 2015
Sep 18, 2015
Sep 17, 2015
Sep 16, 2015
Sep 15, 2015
Sep 14, 2015
Sep 13, 2015
Sep 12, 2015
Sep 11, 2015
Sep 10, 2015
Sep 09, 2015
Sep 08, 2015
Sep 07, 2015
Sep 06, 2015
Sep 05, 2015
Sep 04, 2015
Sep 03, 2015
Sep 02, 2015
Sep 01, 2015
Aug 31, 2015
Aug 30, 2015
Aug 29, 2015
Aug 28, 2015
Aug 27, 2015
Aug 26, 2015
Aug 25, 2015
Aug 24, 2015
Aug 23, 2015
Aug 22, 2015
Aug 21, 2015
Aug 20, 2015
Aug 19, 2015
Aug 18, 2015
Aug 17, 2015
Aug 16, 2015
Aug 15, 2015
Aug 14, 2015
Aug 13, 2015
Aug 12, 2015
Aug 11, 2015
Aug 10, 2015
Aug 09, 2015
Aug 08, 2015
Aug 07, 2015
Aug 06, 2015
Aug 05, 2015
Aug 04, 2015
Aug 03, 2015
Aug 02, 2015
Aug 01, 2015
Jul 31, 2015
Jul 30, 2015
Jul 29, 2015
Jul 28, 2015
Jul 27, 2015
Jul 26, 2015
Jul 25, 2015
Jul 24, 2015
Jul 23, 2015
Jul 22, 2015
Jul 21, 2015
Jul 20, 2015
Jul 19, 2015
Jul 18, 2015
Jul 17, 2015
Jul 16, 2015
Jul 15, 2015
Jul 14, 2015
Jul 13, 2015
Jul 12, 2015
Jul 11, 2015
Jul 10, 2015
Jul 09, 2015
Jul 08, 2015
Jul 07, 2015
Jul 06, 2015
Jul 05, 2015
Jul 04, 2015
Jul 03, 2015

Jul 02, 2015
Jul 01, 2015
Jun 30, 2015
Jun 29, 2015
Jun 28, 2015
Jun 27, 2015
Jun 26, 2015
Jun 25, 2015
Jun 24, 2015
Jun 23, 2015
Jun 22, 2015
Jun 21, 2015
Jun 20, 2015
Jun 19, 2015
Jun 18, 2015
Jun 17, 2015
Jun 16, 2015
Jun 15, 2015
Jun 14, 2015
Jun 13, 2015
Jun 12, 2015
Jun 11, 2015
Jun 10, 2015
Jun 09, 2015
Jun 08, 2015
Jun 07, 2015
Jun 06, 2015
Jun 05, 2015
Jun 04, 2015
Jun 03, 2015
Jun 02, 2015
Jun 01, 2015
May 31, 2015
May 30, 2015
May 29, 2015
May 28, 2015
May 27, 2015
May 26, 2015
May 25, 2015
May 24, 2015
May 23, 2015
May 22, 2015
May 21, 2015
May 20, 2015
May 19, 2015
May 18, 2015
May 17, 2015
May 16, 2015
May 15, 2015
May 14, 2015
May 13, 2015
May 12, 2015
May 11, 2015
May 10, 2015
May 09, 2015
May 08, 2015
May 07, 2015
May 06, 2015
May 05, 2015
May 04, 2015
May 03, 2015
May 02, 2015
May 01, 2015
Apr 30, 2015
Apr 29, 2015
Apr 28, 2015
Apr 27, 2015
Apr 26, 2015
Apr 25, 2015
Apr 24, 2015
Apr 23, 2015
Apr 22, 2015
Apr 21, 2015
Apr 20, 2015
Apr 19, 2015
Apr 18, 2015
Apr 17, 2015
Apr 16, 2015
Apr 15, 2015
Apr 14, 2015
Apr 13, 2015
Apr 12, 2015
Apr 11, 2015
Apr 10, 2015
Apr 09, 2015
Apr 08, 2015
Apr 07, 2015
Apr 06, 2015
Apr 05, 2015
Apr 04, 2015
Apr 03, 2015
Apr 02, 2015
Apr 01, 2015
Mar 31, 2015
Mar 30, 2015
Mar 29, 2015
Mar 28, 2015
Mar 27, 2015
Mar 26, 2015
Mar 25, 2015
Mar 24, 2015
Mar 23, 2015
Mar 22, 2015
Mar 21, 2015
Mar 20, 2015
Mar 19, 2015
Mar 18, 2015
Mar 17, 2015
Mar 16, 2015
Mar 15, 2015
Mar 14, 2015
Mar 13, 2015
Mar 12, 2015
Mar 11, 2015
Mar 10, 2015
Mar 09, 2015
Mar 08, 2015
Mar 07, 2015
Mar 06, 2015
Mar 05, 2015
Mar 04, 2015
Mar 03, 2015
Mar 02, 2015
Mar 01, 2015
Feb 28, 2015
Feb 27, 2015
Feb 26, 2015
Feb 25, 2015
Feb 24, 2015
Feb 23, 2015
Feb 22, 2015
Feb 21, 2015
Feb 20, 2015
Feb 19, 2015
Feb 18, 2015
Feb 17, 2015
Feb 16, 2015
Feb 15, 2015
Feb 14, 2015
Feb 13, 2015
Feb 12, 2015
Feb 11, 2015
Feb 10, 2015
Feb 09, 2015
Feb 08, 2015
Feb 07, 2015
Feb 06, 2015
Feb 05, 2015
Feb 04, 2015
Feb 03, 2015
Feb 02, 2015
Feb 01, 2015
Jan 31, 2015
Jan 30, 2015
Jan 29, 2015
Jan 28, 2015
Jan 27, 2015
Jan 26, 2015
Jan 25, 2015
Jan 24, 2015
Jan 23, 2015
Jan 22, 2015
Jan 21, 2015
Jan 20, 2015
Jan 19, 2015
Jan 18, 2015
Jan 17, 2015
Jan 16, 2015
Jan 15, 2015
Jan 14, 2015
Jan 13, 2015
Jan 12, 2015
Jan 11, 2015
Jan 10, 2015
Jan 09, 2015
Jan 08, 2015
Jan 07, 2015
Jan 06, 2015
Jan 05, 2015
Jan 04, 2015
Jan 03, 2015
Jan 02, 2015
Jan 01, 2015
Dec 31, 2014
Dec 30, 2014
Dec 29, 2014
Dec 28, 2014
Dec 27, 2014
Dec 26, 2014
Dec 25, 2014
Dec 24, 2014
Dec 23, 2014
Dec 22, 2014
Dec 21, 2014
Dec 20, 2014
Dec 19, 2014
Dec 18, 2014
Dec 17, 2014
Dec 16, 2014
Dec 15, 2014
Dec 14, 2014
Dec 13, 2014
Dec 12, 2014
Dec 11, 2014
Dec 10, 2014
Dec 09, 2014
Dec 08, 2014
Dec 07, 2014
Dec 06, 2014
Dec 05, 2014
Dec 04, 2014
Dec 03, 2014
Dec 02, 2014
Dec 01, 2014
Nov 30, 2014
Nov 29, 2014
Nov 28, 2014
Nov 27, 2014
Nov 26, 2014
Nov 25, 2014
Nov 24, 2014
Nov 23, 2014
Nov 22, 2014
Nov 21, 2014
Nov 20, 2014
Nov 19, 2014
Nov 18, 2014
Nov 17, 2014
Nov 16, 2014
Nov 15, 2014
Nov 14, 2014
Nov 13, 2014
Nov 12, 2014
Nov 11, 2014
Nov 10, 2014
Nov 09, 2014
Nov 08, 2014
Nov 07, 2014
Nov 06, 2014
Nov 05, 2014
Nov 04, 2014
Nov 03, 2014
Nov 02, 2014
Nov 01, 2014
Oct 31, 2014
Oct 30, 2014
Oct 29, 2014
Oct 28, 2014
Oct 27, 2014
Oct 26, 2014
Oct 25, 2014
Oct 24, 2014
Oct 23, 2014
Oct 22, 2014
Oct 21, 2014
Oct 20, 2014
Oct 19, 2014
Oct 18, 2014
Oct 17, 2014
Oct 16, 2014
Oct 15, 2014
Oct 14, 2014
Oct 13, 2014
Oct 12, 2014
Oct 11, 2014
Oct 10, 2014
Oct 09, 2014
Oct 08, 2014
Oct 07, 2014
Oct 06, 2014
Oct 05, 2014
Oct 04, 2014
Oct 03, 2014
Oct 02, 2014
Oct 01, 2014
Sep 30, 2014
Sep 29, 2014
Sep 28, 2014
Sep 27, 2014
Sep 26, 2014
Sep 25, 2014
Sep 24, 2014
Sep 23, 2014
Sep 22, 2014
Sep 21, 2014
Sep 20, 2014
Sep 19, 2014
Sep 18, 2014
Sep 17, 2014
Sep 16, 2014
Sep 15, 2014
Sep 14, 2014
Sep 13, 2014
Sep 12, 2014
Sep 11, 2014
Sep 10, 2014
Sep 09, 2014
Sep 08, 2014
Sep 07, 2014
Sep 06, 2014
Sep 05, 2014
Sep 04, 2014
Sep 03, 2014
Sep 02, 2014
Sep 01, 2014
Aug 31, 2014
Aug 30, 2014
Aug 29, 2014
Aug 28, 2014
Aug 27, 2014
Aug 26, 2014
Aug 25, 2014
Aug 24, 2014
Aug 23, 2014
Aug 22, 2014
Aug 21, 2014
Aug 20, 2014
Aug 19, 2014
Aug 18, 2014
Aug 17, 2014
Aug 16, 2014
Aug 15, 2014
Aug 14, 2014
Aug 13, 2014
Aug 12, 2014
Aug 11, 2014
Aug 10, 2014
Aug 09, 2014
Aug 08, 2014
Aug 07, 2014
Aug 06, 2014
Aug 05, 2014
Aug 04, 2014
Aug 03, 2014
Aug 02, 2014
Aug 01, 2014
Jul 31, 2014
Jul 30, 2014
Jul 29, 2014
Jul 28, 2014
Jul 27, 2014
Jul 26, 2014
Jul 25, 2014
Jul 24, 2014
Jul 23, 2014
Jul 22, 2014
Jul 21, 2014
Jul 20, 2014
Jul 19, 2014
Jul 18, 2014
Jul 17, 2014
Jul 16, 2014
Jul 15, 2014
Jul 14, 2014
Jul 13, 2014
Jul 12, 2014
Jul 11, 2014
Jul 10, 2014
Jul 09, 2014
Jul 08, 2014
Jul 07, 2014
Jul 06, 2014
Jul 05, 2014
Jul 04, 2014
Jul 03, 2014
Jul 02, 2014
Jul 01, 2014
Jun 30, 2014
Jun 29, 2014
Jun 28, 2014
Jun 27, 2014
Jun 26, 2014
Jun 25, 2014
Jun 24, 2014
Jun 23, 2014
Jun 22, 2014
Jun 21, 2014
Jun 20, 2014
Jun 19, 2014
Jun 18, 2014
Jun 17, 2014
Jun 16, 2014
Jun 15, 2014
Jun 14, 2014
Jun 13, 2014
Jun 12, 2014
Jun 11, 2014
Jun 10, 2014
Jun 09, 2014
Jun 08, 2014
Jun 07, 2014
Jun 06, 2014
Jun 05, 2014
Jun 04, 2014
Jun 03, 2014
Jun 02, 2014
Jun 01, 2014
May 31, 2014
May 30, 2014
May 29, 2014
May 28, 2014
May 27, 2014
May 26, 2014
May 25, 2014
May 24, 2014
May 23, 2014
May 22, 2014
May 21, 2014
May 20, 2014
May 19, 2014
May 18, 2014
May 17, 2014
May 16, 2014
May 15, 2014
May 14, 2014
May 13, 2014
May 12, 2014
May 11, 2014
May 10, 2014
May 09, 2014
May 08, 2014
May 07, 2014
May 06, 2014
May 05, 2014
May 04, 2014
May 03, 2014
May 02, 2014
May 01, 2014
Apr 30, 2014
Apr 29, 2014
Apr 28, 2014
Apr 27, 2014
Apr 26, 2014
Apr 25, 2014
Apr 24, 2014
Apr 23, 2014
Apr 22, 2014
Apr 21, 2014
Apr 20, 2014
Apr 19, 2014
Apr 18, 2014
Apr 17, 2014
Apr 16, 2014
Apr 15, 2014
Apr 14, 2014
Apr 13, 2014
Apr 12, 2014
Apr 11, 2014
Apr 10, 2014
Apr 09, 2014
Apr 08, 2014
Apr 07, 2014
Apr 06, 2014
Apr 05, 2014
Apr 04, 2014
Apr 03, 2014
Apr 02, 2014
Apr 01, 2014
Mar 31, 2014
Mar 30, 2014
Mar 29, 2014
Mar 28, 2014
Mar 27, 2014
Mar 26, 2014
Mar 25, 2014
Mar 24, 2014
Mar 23, 2014
Mar 22, 2014
Mar 21, 2014
Mar 20, 2014
Mar 19, 2014
Mar 18, 2014
Mar 17, 2014
Mar 16, 2014
Mar 15, 2014
Mar 14, 2014
Mar 13, 2014
Mar 12, 2014
Mar 11, 2014
Mar 10, 2014
Mar 09, 2014
Mar 08, 2014
Mar 07, 2014
Mar 06, 2014
Mar 05, 2014
Mar 04, 2014
Mar 03, 2014
Mar 02, 2014
Mar 01, 2014
Feb 28, 2014
Feb 27, 2014
Feb 26, 2014
Feb 25, 2014
Feb 24, 2014
Feb 23, 2014
Feb 22, 2014
Feb 21, 2014
Feb 20, 2014
Feb 19, 2014
Feb 18, 2014
Feb 17, 2014
Feb 16, 2014
Feb 15, 2014
Feb 14, 2014
Feb 13, 2014
Feb 12, 2014
Feb 11, 2014
Feb 10, 2014
Feb 09, 2014
Feb 08, 2014
Feb 07, 2014
Feb 06, 2014
Feb 05, 2014
Feb 04, 2014
Feb 03, 2014
Feb 02, 2014
Feb 01, 2014
Jan 31, 2014
Jan 30, 2014
Jan 29, 2014
Jan 28, 2014
Jan 27, 2014
Jan 26, 2014
Jan 25, 2014
Jan 24, 2014
Jan 23, 2014
Jan 22, 2014
Jan 21, 2014
Jan 20, 2014
Jan 19, 2014
Jan 18, 2014
Jan 17, 2014
Jan 16, 2014
Jan 15, 2014
Jan 14, 2014
Jan 13, 2014
Jan 12, 2014
Jan 11, 2014
Jan 10, 2014
Jan 09, 2014
Jan 08, 2014
Jan 07, 2014
Jan 06, 2014
Jan 05, 2014
Jan 04, 2014
Jan 03, 2014
Jan 02, 2014
Jan 01, 2014
Dec 31, 2013
Dec 30, 2013
Dec 29, 2013
Dec 28, 2013
Dec 27, 2013
Dec 26, 2013
Dec 25, 2013
Dec 24, 2013
Dec 23, 2013
Dec 22, 2013
Dec 21, 2013
Dec 20, 2013
Dec 19, 2013
Dec 18, 2013
Dec 17, 2013
Dec 16, 2013
Dec 15, 2013
Dec 14, 2013
Dec 13, 2013
Dec 12, 2013
Dec 11, 2013
Dec 10, 2013
Dec 09, 2013
Dec 08, 2013
Dec 07, 2013
Dec 06, 2013
Dec 05, 2013
Dec 04, 2013
Dec 03, 2013
Dec 02, 2013
Dec 01, 2013
Nov 30, 2013
Nov 29, 2013
Nov 28, 2013
Nov 27, 2013
Nov 26, 2013
Nov 25, 2013
Nov 24, 2013
Nov 23, 2013
Nov 22, 2013
Nov 21, 2013
Nov 20, 2013
Nov 19, 2013
Nov 18, 2013
Nov 17, 2013
Nov 16, 2013
Nov 15, 2013
Nov 14, 2013
Nov 13, 2013
Nov 12, 2013
Nov 11, 2013
Nov 10, 2013
Nov 09, 2013
Nov 08, 2013
Nov 07, 2013
Nov 06, 2013
Nov 05, 2013
Nov 04, 2013
Nov 03, 2013
Nov 02, 2013
Nov 01, 2013
Oct 31, 2013
Oct 30, 2013
Oct 29, 2013
Oct 28, 2013
Oct 27, 2013
Oct 26, 2013
Oct 25, 2013
Oct 24, 2013
Oct 23, 2013
Oct 22, 2013
Oct 21, 2013
Oct 20, 2013
Oct 19, 2013
Oct 18, 2013
Oct 17, 2013
Oct 16, 2013
Oct 15, 2013
Oct 14, 2013
Oct 13, 2013
Oct 12, 2013
Oct 11, 2013
Oct 10, 2013
Oct 09, 2013
Oct 08, 2013
Oct 07, 2013
Oct 06, 2013
Oct 05, 2013
Oct 04, 2013
Oct 03, 2013
Oct 02, 2013
Oct 01, 2013
Sep 30, 2013
Sep 29, 2013
Sep 28, 2013
Sep 27, 2013
Sep 26, 2013
Sep 25, 2013
Sep 24, 2013
Sep 23, 2013
Sep 22, 2013
Sep 21, 2013
Sep 20, 2013
Sep 19, 2013
Sep 18, 2013
Sep 17, 2013
Sep 16, 2013
Sep 15, 2013
Sep 14, 2013
Sep 13, 2013
Sep 12, 2013
Sep 11, 2013
Sep 10, 2013
Sep 09, 2013
Sep 08, 2013
Sep 07, 2013
Sep 06, 2013
Sep 05, 2013
Sep 04, 2013
Sep 03, 2013
Sep 02, 2013
Sep 01, 2013
Aug 31, 2013
Aug 30, 2013
Aug 29, 2013
Aug 28, 2013
Aug 27, 2013
Aug 26, 2013
Aug 25, 2013
Aug 24, 2013
Aug 23, 2013
Aug 22, 2013
Aug 21, 2013
Aug 20, 2013
Aug 19, 2013
Aug 18, 2013
Aug 17, 2013
Aug 16, 2013
Aug 15, 2013
Aug 14, 2013
Aug 13, 2013
Aug 12, 2013
Aug 11, 2013
Aug 10, 2013
Aug 09, 2013
Aug 08, 2013
Aug 07, 2013
Aug 06, 2013
Aug 05, 2013
Aug 04, 2013
Aug 03, 2013
Aug 02, 2013
Aug 01, 2013
Jul 31, 2013
Jul 30, 2013
Jul 29, 2013
Jul 28, 2013
Jul 27, 2013
Jul 26, 2013
Jul 25, 2013
Jul 24, 2013
Jul 23, 2013
Jul 22, 2013
Jul 21, 2013
Jul 20, 2013
Jul 19, 2013
Jul 18, 2013
Jul 17, 2013
Jul 16, 2013
Jul 15, 2013
Jul 14, 2013
Jul 13, 2013
Jul 12, 2013
Jul 11, 2013
Jul 10, 2013
Jul 09, 2013
Jul 08, 2013
Jul 07, 2013
Jul 06, 2013
Jul 05, 2013
Jul 04, 2013
Jul 03, 2013
Jul 02, 2013
Jul 01, 2013
Jun 30, 2013
Jun 29, 2013
Jun 28, 2013
Jun 27, 2013
Jun 26, 2013
Jun 25, 2013
Jun 24, 2013
Jun 23, 2013
Jun 22, 2013
Jun 21, 2013
Jun 20, 2013
Jun 19, 2013
Jun 18, 2013
Jun 17, 2013
Jun 16, 2013
Jun 15, 2013
Jun 14, 2013
Jun 13, 2013
Jun 12, 2013
Jun 11, 2013
Jun 10, 2013
Jun 09, 2013
Jun 08, 2013
Jun 07, 2013
Jun 06, 2013
Jun 05, 2013
Jun 04, 2013
Jun 03, 2013
Jun 02, 2013
Jun 01, 2013
May 31, 2013
May 30, 2013
May 29, 2013
May 28, 2013
May 27, 2013
May 26, 2013
May 25, 2013
May 24, 2013
May 23, 2013
May 22, 2013
May 21, 2013
May 20, 2013
May 19, 2013
May 18, 2013
May 17, 2013
May 16, 2013
May 15, 2013
May 14, 2013
May 13, 2013
May 12, 2013
May 11, 2013
May 10, 2013
May 09, 2013
May 08, 2013
May 07, 2013
May 06, 2013
May 05, 2013
May 04, 2013
May 03, 2013
May 02, 2013
May 01, 2013
Apr 30, 2013
Apr 29, 2013
Apr 28, 2013

In [121]:
# now , let us put all of this into a structured format 
# create a list for each item that we want 
list_date=[] 
list_open=[]
list_high=[] 
list_low =[]
list_close=[] 
list_volume=[] 
list_marketcap=[]

for x in range(0,len(divclass2)):
    divclass4=divclass2[x].find_all("td")
    s1=str(divclass4[0])
    s1=str(divclass4[0])
    s2=str(divclass4[1])
    s3=str(divclass4[2])
    s4=str(divclass4[3])
    s5=str(divclass4[4])
    s6=str(divclass4[5])
    s7=str(divclass4[6])
    list_date.append(s1[s1.find(start_fordate)+len(start_fordate):s1.rfind(end)])
    list_open.append(s2[s2.find(start_normal)+len(start_normal):s2.rfind(end)])
    list_high.append(s3[s3.find(start_normal)+len(start_normal):s3.rfind(end)])
    list_low.append(s4[s4.find(start_normal)+len(start_normal):s4.rfind(end)])
    list_close.append(s5[s5.find(start_normal)+len(start_normal):s5.rfind(end)])
    list_volume.append(s6[s6.find(start_normal)+len(start_normal):s6.rfind(end)])
    list_marketcap.append(s7[s7.find(start_normal)+len(start_normal):s7.rfind(end)])
    
    
print("done")

done

In [124]:
# put all of these lists in a single dataframe
finaldf = pd.DataFrame(
    {'Date': list_date,
     'Open': list_open,
     'High': list_high, 
     'Low' : list_low, 
     'Close' : list_close, 
     'Volume' : list_volume, 
     'MarketCap' : list_marketcap
    })
print("done")

done

In [126]:
# view a sample of the dataframe
finaldf.head()

,Close,Date,High,Low,MarketCap,Open,Volume
0,4065.20,"Sep 18, 2017",4079.23,3591.09,"59,514,100,000",3591.09,"1,943,210,000"
1,3582.88,"Sep 17, 2017",3664.81,3445.64,"59,757,800,000",3606.28,"1,239,150,000"
2,3625.04,"Sep 16, 2017",3808.84,3487.79,"60,271,600,000",3637.75,"1,818,400,000"
3,3637.52,"Sep 15, 2017",3733.45,2946.62,"52,453,500,000",3166.30,"4,148,070,000"
4,3154.95,"Sep 14, 2017",3920.60,3153.86,"64,191,600,000",3875.37,"2,716,310,000"

In [127]:
# You can easily export this as a csv file 
# before doing this , make sure you have a blank csv file . In this case , a file called lulz.csv 
# Change the filepath as required , uncomment the below line and run it  
#finaldf.to_csv('C:\\Users\\raosa\\Desktop\\lulz.csv', sep=',', encoding='utf-8')
print("done")

done

In [151]:
# We are done with the data for bitcoin , but we might also want to examine what other currencies there are 
page1 = requests.get("https://coinmarketcap.com/all/views/all/")
# A 200 response means that the request was executed
page1

In [213]:
soup = BeautifulSoup(page1.content, 'html.parser')
currencyname1=list(soup.children)[10]
currencyname2=list(currencyname1.children)[5]
currencyname3=list(currencyname2.children)[7]
currencyname4 = currencyname3.find_all("td",{"class":"no-wrap currency-name"})

#currencyname5 = currencyname4[0]
#currencyname6=list(currencyname5)
#currencyname7=currencyname6[3]
#currencyname7

In [218]:
for i in range(0,len(currencyname4)):
    currencyname6=list(currencyname4[i])
    currencyname7=currencyname6[3]
    start_currency='>'
    end_currency='<'
    currencystring=str(currencyname7)
    currencystring1=(currencystring[currencystring.find(start_fordate)+len(start_fordate):currencystring.rfind(end)])
    print(currencystring1)
    
    # too lazy to figure out how to get the junk before the name starts out 
    # copy this into excel , use convert text to columns 
    # use > as a delimiter 
    # done

bitcoin/">Bitcoin
ethereum/">Ethereum
bitcoin-cash/">Bitcoin Cash
ripple/">Ripple
litecoin/">Litecoin
dash/">Dash
nem/">NEM
iota/">IOTA
monero/">Monero
ethereum-classic/">Ethereum Classic
neo/">NEO
ego/">OmiseGO
bitconnect/">BitConnect
lisk/">Lisk
/">Qtum
stratis/">Stratis
er/">Tether
waves/">Waves
zcash/">Zcash
ark/">Ark
steem/">Steem
safecoin/">MaidSafeCoin
bytecoin-bcn/">Bytecoin
">EOS
m-network-tokens/">Golem
c-attention-token/">Basic Attenti...
/">TenX
bitshares/">BitShares
r/">Augur
hshare/">Hshare
stellar/">Stellar Lumens
komodo/">Komodo
decred/">Decred
pivx/">PIVX
taseum/">Veritaseum
l/">Metal
nexus/">Nexus
factom/">Factom
omi/">Iconomi
xdao/">DigixDAO
byteball/">Byteball Bytes
siacoin/">Siacoin
c/">Civic
digibyte/">DigiByte
lous/">Populous
is-gno/">Gnosis
bitcoindark/">BitcoinDark
r/">Ardor
gamecredits/">GameCredits
ulardtv/">SingularDTV
>0x
blocknet/">Blocknet
dogecoin/">Dogecoin
syscoin/">Syscoin
air/">FunFair
co/">Monaco
rnity/">Aeternity
or/">Bancor
lykke/">Lykke
verge/">Verge
us/">Status
nce-coin/">Binance Coin
">Gas
bitdeal/">Bitdeal
nxt/">Nxt
less/">Edgeless
on/">Aragon
particl/">Particl
iocoin/">I/O Coin
ubiq/">Ubiq
firstcoin/">FirstCoin
uence/">Bitquence
nav-coin/">NAV Coin
s/">Wings
und-it/">Cofound.it
rise/">Rise
lego/">MobileGo
gxshares/">GXShares
m/">Bytom
j/">Storj
nolimitcoin/">NoLimitCoin
">iExec RLC
gulden/">Gulden
ion/">Tierion
cloakcoin/">CloakCoin
ar/">Pillar
elastic/">Elastic
tha/">Monetha
on/">Walton
n/">Melon
gers/">Triggers
faircoin/">FairCoin
ncard/">TokenCard
peercoin/">Peercoin
okcash/">OKCash
vertcoin/">Vertcoin
ring/">Loopring
llo-delta/">Agrello
net/">AdEx
leocoin/">LEOcoin
tblood/">FirstBlood
to/">Rialto
counterparty/">Counterparty
aidos-kuneen/">Aidos Kuneen
entory/">Patientory
decent/">DECENT
tum-resistant-ledger/">Quantum Resis...
/">TaaS
roll/">Etheroll
ership/">Mothership
reddcoin/">ReddCoin
t/">WeTrust
emercoin/">Emercoin
the-champcoin/">The ChampCoin
zcoin/">ZCoin
/">SONM
viacoin/">Viacoin
d/">Round
monacoin/">MonaCoin
rict0x/">district0x
crown/">Crown
um/">Xaurum
ken/">adToken
bius/">Polybius
iment/">Santiment Net...
ion/">ION
rnet-unity/">SuperNET
namecoin/">Namecoin
r/">Lunyr
um/">Nexium
bitbay/">BitBay
clams/">Clams
unobtanium/">Unobtanium
spreadcoin/">SpreadCoin
raire/">Numeraire
expanse/">Expanse
ce/">vSlice
groestlcoin/">Groestlcoin
reum-movie-venture/">Ethereum Movi...
/">Stox
diamond/">Diamond
niq/">Humaniq
-exchange-coin/">Safe Exchange...
monetaryunit/">MonetaryUnit
dash/">CoinDash
erium/">Mysterium
blackcoin/">BlackCoin
burst/">Burst
potcoin/">PotCoin
skycoin/">Skycoin
o/">Credo
sibcoin/">SIBCoin
/">Po.et
radium/">Radium
tum/">Quantum
rubycoin/">Rubycoin
reo/">Synereo
library-credit/">LBRY Credits
as-tokens/">Agoras Tokens
zencash/">ZenCash
omni/">Omni
shift/">Shift
y/">XPlay
peerplays-ppy/">Peerplays
atc-coin/">ATC Coin
digitalnote/">DigitalNote
nobank/">Chronobank
golos/">Golos
mooncoin/">Mooncoin
salus/">SaluS
energycoin/">Energycoin
gambit/">Gambit
stfeed/">InvestFeed
neblio/">Neblio
y/">Matchpool
s-community-token/">Waves Communi...
tus/">Aventus
rr/">Wagerr
gridcoin/">GridCoin
m-city/">Swarm City
aeon/">Aeon
greencoin/">Greencoin
lomocoin/">LoMoCoin
bits/">Databits
xcurrency/">XCurrency
raiblocks/">RaiBlocks
neoscoin/">NeosCoin
e-coin/">E-coin
einsteinium/">Einsteinium
y/">Propy
it/">Ecobit
/">BCAP
coin/">Soarcoin
as/">Primas
voxels/">Voxels
dger/">iXledger
e-dinar-coin/">E-Dinar Coin
martexcoin/">MarteXcoin
s/">OBITS
florincoin/">FlorinCoin
q/">Nimiq
anx/">OpenAnx
rus/">Darcrus
vericoin/">VeriCoin
rystals/">Bitcrystals
prizm/">PRIZM
ktix/">Blocktix
smartcash/">SmartCash
novacoin/">Novacoin
spectrecoin/">Spectrecoin
feathercoin/">Feathercoin
toacoin/">ToaCoin
eccoin/">E-Currency Coin
y-ingot/">Unity Ingot
pinkcoin/">PinkCoin
korecoin/">KoreCoin
musicoin/">Musicoin
casino/">DAO.Casino
on/">Pluton
nt/">Incent
sphere/">Sphere
asch/">Asch
xtrabytes/">XTRABYTES
solarcoin/">SolarCoin
daxxcoin/">DaxxCoin
-cash/">Pepe Cash
dnotes/">DNotes
vcash/">Vcash
stealthcoin/">Stealthcoin
compcoin/">Compcoin
itbit/">Creditbit
sequence/">Sequence
kcat/">BlockCAT
">APX
blitzcash/">Blitzcash
bitcoin-plus/">Bitcoin Plus
ect-decorum/">Project Decorum
flip/">TrueFlip
t-token/">MyBit Token
coin/">Bankcoin
exclusivecoin/">ExclusiveCoin
bitsend/">BitSend
embercoin/">EmberCoin
">NVO
ingcoin/">FoldingCoin
bitbean/">BitBean
goldcoin/">GoldCoin
applebyte/">ArtByte
auroracoin/">Auroracoin
dubaicoin-dbix/">DubaiCoin
k/">Qwark
dimecoin/">Dimecoin
pascal-coin/">Pascal Coin
curecoin/">Curecoin
uits-of-value/">Circuits of V...
bitswift/">Bitswift
htmlcoin/">HTMLCOIN
heat-ledger/">HEAT
/">Dent
equitrader/">EquiTrader
synergy/">Synergy
bitcore/">Bitcore
rdie/">NEVERDIE
putincoin/">PutinCoin
/">Jinn
condensate/">Condensate
whitecoin/">WhiteCoin
posw-coin/">PoSW Coin
yptotel/">EncryptoTel
belacoin/">Bela
happycoin/">Happycoin
in/">ZrCoin
ares/">NuShares
sprouts/">Sprouts
europecoin/">EuropeCoin
pesetacoin/">Pesetacoin
global-currency-reserve/">Global Curren...
signatum/">Signatum
myriad/">Myriad
ontract/">SunContract
espers/">Espers
zclassic/">ZClassic
steem-dollars/">Steem Dollars
geocoin/">GeoCoin
ybcoin/">YbCoin
rs/">Embers
dynamic/">Dynamic
syndicate/">Syndicate
breakout-stake/">Breakout Stake
dopecoin/">DopeCoin
neutron/">Neutron
/">Opus
bata/">Bata
primecoin/">Primecoin
centurion/">Centurion
bitmark/">Bitmark
atmos/">Atmos
-estate-tokens/">REX
hempcoin/">HempCoin
wild-beast-block/">Wild Beast Block
colossuscoin-v2/">Colossuscoin V2
breakout/">Breakout
visio/">Visio
deeponion/">DeepOnion
chaincoin/">ChainCoin
crave/">Crave
trustplus/">TrustPlus
zeitcoin/">Zeitcoin
2give/">2GIVE
transfercoin/">TransferCoin
evergreencoin/">EverGreenCoin
linda/">Linda
token/">FuckToken
acoin/">Dentacoin
memetic/">Memetic
terracoin/">Terracoin
s/">Tokes
e/">VOISE
veriumreserve/">VeriumReserve
ta/">Starta
earthcoin/">EarthCoin
cannabiscoin/">CannabisCoin
hush/">Hush
adzcoin/">Adzcoin
vtorrent/">vTorrent
iluscoin/">NautilusCoin
-watt-token/">Giga Watt Token
nds-room/">Legends Room
monacocoin/">MonacoCoin
creativecoin/">Creativecoin
cryptogenic-bullion/">Crypto Bullion
nlab/">Oceanlab
mintcoin/">Mintcoin
-platform/">Link Platform
vivo/">VIVO
huntercoin/">HunterCoin
yourselfnow/">FundYourselfNow
its/">Ethbits
magi/">Magi
coin/">SkinCoin
zennies/">Zennies
tao/">Tao
reum/">Minereum
cryptocarbon/">CryptoCarbon
nto/">Fujinto
ares/">AdShares
parkbyte/">ParkByte
startcoin/">Startcoin
toping/">CryptoPing
ury/">Mercury
vpncoin/">VPNCoin
smileycoin/">SmileyCoin
luckchain/">LuckChain
arcticcoin/">ArcticCoin
e-gulden/">e-Gulden
fedoracoin/">FedoraCoin
hyperstake/">HyperStake
riecoin/">Riecoin
ixcoin/">Ixcoin
piecoin/">PIECoin
growers-international/">Growers Inter...
token/">EOT Token
1337coin/">1337
capricoin/">Capricoin
fincoin/">FinCoin
maxcoin/">MaxCoin
insanecoin-insn/">InsaneCoin
renos/">Renos
quark/">Quark
helleniccoin/">Helleniccoin
iticoin/">iTicoin
litedoge/">LiteDoge
cryptonite/">Cryptonite
dotcoin/">Dotcoin
inflationcoin/">InflationCoin
808coin/">808Coin
sumokoin/">Sumokoin
oken/">DT Token
mergecoin/">MergeCoin
bytecent/">Bytecent
nubits/">NuBits
hicoin/">HiCoin
worldcoin/">WorldCoin
sexcoin/">Sexcoin
influxcoin/">Influxcoin
emoneypower/">EMoneyPower
fastcoin/">Fastcoin
tal-developers-fund/">DigitalDevelo...
credits/">StarCredits
megacoin/">Megacoin
krypstal/">Krypstal
woodcoin/">Woodcoin
rs-reward-token/">Miners' Rewar...
coin/">Remicoin
b3coin/">B3Coin
infinitecoin/">Infinitecoin
eternity/">Eternity
unitus/">Unitus
kekcoin/">KekCoin
ter-byte/">Monster Byte
zetacoin/">Zetacoin
netko/">Netko
sgo/">WavesGo
zoin/">Zoin
eboostcoin/">eBoost
tagcoin/">TagCoin
tychocoin/">Tychocoin
denarius-dnr/">Denarius
bitradio/">Bitradio
unify/">Unify
linx/">Linx
vsync-vsx/">Vsync
carboncoin/">Carboncoin
canada-ecoin/">Canada eCoin
virtacoinplus/">Virtacoinplus
moin/">Moin
prototanium/">Prototanium
vsync/">Vsync
unbreakablecoin/">UnbreakableCoin
fimkrypto/">FIMKrypto
bitbar/">BitBar
das/">DAS
procurrency/">ProCurrency
fujicoin/">FujiCoin
xp/">XP
oin/">FUNCoin
zccoin/">ZcCoin
ium/">Newbium
shorty/">Shorty
cream/">Cream
noblecoin/">NobleCoin
dinastycoin/">Dinastycoin
machinecoin/">Machinecoin
netcoin/">NetCoin
hitcoin/">HitCoin
onix/">Onix
karbowanec/">Karbowanec
britcoin/">BritCoin
ettetoken/">RouletteToken
rubies/">Rubies
postcoin/">PostCoin
coinonatx/">CoinonatX
petrodollar/">PetroDollar
women/">WomenCoin
e/">iDice
zero/">Zero
8bit/">8Bit
sean/">BitAsean
42-coin/">42-coin
mazacoin/">MazaCoin
scorecoin/">Scorecoin
trumpcoin/">TrumpCoin
version/">Version
deutsche-emark/">Deutsche eMark
atomic-coin/">Atomic Coin
gcoin/">GCoin
rexe/">FuturXe
platinumbar/">PlatinumBAR
elcoin-el/">Elcoin
thegcccoin/">TheGCCcoin
mao-zedong/">Mao Zedong
titcoin/">Titcoin
virta-unique-coin/">Virta Unique ...
mineum/">Mineum
ratecoin/">Ratecoin
rupaya/">Rupaya
flaxscript/">Flaxscript
in/">Yocoin
coin/">Dalecoin
o-bux/">Ripto Bux
chronos/">Chronos
goldblocks/">GoldBlocks
coin/">TileCoin
hodlcoin/">HOdlcoin
zurcoin/">Zurcoin
rupee/">Rupee
solaris/">Solaris
tickets/">Tickets
master-swiscoin/">Master Swiscoin
corgicoin/">CorgiCoin
berncash/">BERNcash
electra/">Electra
chancoin/">ChanCoin
blakestar/">BlakeStar
guccionecoin/">GuccioneCoin
biblepay/">BiblePay
cryptojacks/">Cryptojacks
icobid/">ICOBID
litecoin-plus/">Litecoin Plus
ecocoin/">EcoCoin
iconic/">Iconic
campuscoin/">CampusCoin
antibitcoin/">AntiBitcoin
asiadigicoin/">Asiadigicoin
crevacoin/">CrevaCoin
doubloon/">Doubloon
prcoin/">PRCoin
chncoin/">CHNCoin
briacoin/">BriaCoin
argentum/">Argentum
firecoin/">Firecoin
sixeleven/">SixEleven
crypto/">Crypto
macron/">MACRON
eryllium/">Eryllium
droxne/">DROXNE
kingn-coin/">KingN Coin
sojourn/">Sojourn
allion/">Allion
comet/">Comet
goldpieces/">GoldPieces
slevin/">Slevin
kronecoin/">Kronecoin
veros/">Veros
frazcoin/">Frazcoin
applecoin-apw/">AppleCoin
solarflarecoin/">Solarflarecoin
litecoin-ultra/">LiteCoin Ultra
rsgpcoin/">RSGPcoin
wexcoin/">Wexcoin
levoplus/">LevoPlus
litebitcoin/">LiteBitcoin
ebittree-coin/">Ebittree Coin
harmonycoin-hmc/">HarmonyCoin
reecoin/">ReeCoin
abncoin/">Abncoin
eb3-coin/">EB3 Coin
">ICO
metaverse/">Metaverse ETP
de-token/">Arcade Token
ny/">bitCNY
lechain/">OracleChain
albase/">Primalbase Token
in/">CVCoin
sd/">bitUSD
stakecoin-stcn/">Stakecoin
ea-poker/">Pangea Poker
and/">Bitland
bluecoin/">BlueCoin
phoi/">Adelphoi
openledger/">ICO OpenLedger
asiacoin/">AsiaCoin
oin-alt/">Altcoin
ark-coin/">Bitpark Coin
yashcoin/">YashCoin
kpay/">BlockPay
y/">InPay
audiocoin/">AudioCoin
pandacoin-pnd/">Pandacoin
casinocoin/">CasinoCoin
i0coin/">I0Coin
oin/">LTBcoin
ultimate-secure-cash/">Ultimate Secu...
s/">Janus
r-for-the-rest-of-the-world/">E4ROW
bits/">Rustbits
metalcoin/">MetalCoin
riya/">Etheriya
shadowcash/">ShadowCash
octanox/">Octanox
incakoin/">IncaKoin
cryptcoin/">CryptCoin
bunnycoin/">BunnyCoin
teslacoin/">TeslaCoin
no/">Casino
al/">CoEval
fantomcoin/">Fantomcoin
globalcoin/">GlobalCoin
bitz/">Bitz
swaptoken/">SwapToken
reign-hero/">Sovereign Hero
cagecoin/">CageCoin
draftcoin/">DraftCoin
devcoin/">Devcoin
orbitcoin/">Orbitcoin
toforecast/">CryptoForecast
-pepe-party/">Rare Pepe Party
ufo-coin/">UFO Coin
omy/">Goodomy
fuelcoin/">FuelCoin
stress/">Stress
kobocoin/">Kobocoin
ultracoin/">UltraCoin
the-cypherfunks/">The Cypherfunks
swing/">Swing
trollcoin/">Trollcoin
supercoin/">SuperCoin
ow-token/">Shadow Token
pakcoin/">Pakcoin
dashcoin/">Dashcoin
btctalkcoin/">BTCtalkcoin
veltor/">Veltor
russiacoin/">RussiaCoin
ambercoin/">AmberCoin
unicoin/">UniCoin
anoncoin/">Anoncoin
/">BTSR
universal-currency/">Universal Cur...
smartcoin/">SmartCoin
cannacoin/">Cannacoin
bitstar/">Bitstar
piggycoin/">Piggycoin
o2olondoncoin/">020LondonCoin
gaia/">GAIA
aurumcoin/">AurumCoin
litebar/">LiteBar
triangles/">Triangles
joulecoin/">Joulecoin
malcoin/">Malcoin
truckcoin/">Truckcoin
bittokens/">BitTokens
paycoin2/">PayCoin
flycoin/">Flycoin
phoenixcoin/">Phoenixcoin
lottocoin/">LottoCoin
tc/">bitBTC
jin-coin/">Jin Coin
newyorkcoin/">NewYorkCoin
slimcoin/">Slimcoin
fluttercoin/">FlutterCoin
gameunits/">GameUnits
francs/">Francs
bigup/">BigUp
lanacoin/">LanaCoin
valorbit/">Valorbit
bottlecaps/">Bottlecaps
purevidz/">PureVidz
chesscoin/">ChessCoin
ilver/">bitSilver
pesobit/">Pesobit
qubitcoin/">QubitCoin
ohm-wallet/">OHM
kushcoin/">KushCoin
usde/">USDe
emerald/">Emerald Crypto
yacoin/">Yacoin
acoin/">Acoin
universe/">Universe
aming/">MTMGaming
eurocoin/">Eurocoin
nyancoin/">Nyancoin
icoin/">iCoin
parallelcoin/">ParallelCoin
bitcoin-scrypt/">Bitcoin Scrypt
bitcurrency/">Bitcurrency
quazarcoin/">QuazarCoin
revolvercoin/">RevolverCoin
pascal-lite/">Pascal Lite
wayguide/">WayGuide
kilocoin/">KiloCoin
0/">Bit20
freicoin/">Freicoin
sproutsextreme/">SproutsExtreme
tekcoin/">TEKcoin
goldreserve/">GoldReserve
darsek/">Darsek
old/">bitGold
kibicoin/">KibiCoin
honey/">Honey
globalboost-y/">GlobalBoost-Y
hempcoin-hmp/">HempCoin
tittiecoin/">TittieCoin
swagbucks/">SwagBucks
cypher/">Cypher
tigercoin/">Tigercoin
mojocoin/">MojoCoin
octocoin/">OctoCoin
digicube/">DigiCube
sterlingcoin/">Sterlingcoin
oin/">Jetcoin
gpu-coin/">GPU Coin
joincoin/">Joincoin
prime-xi/">Prime-XI
coin2-1/">Coin2.1
bolivarcoin/">Bolivarcoin
digitalcoin/">Digitalcoin
blakecoin/">Blakecoin
ur/">bitEUR
grantcoin/">Grantcoin
boostcoin/">BoostCoin
px/">PX
cannation/">Cannation
sacoin/">SACoin
c-bit/">C-Bit
theresa-may-coin/">Theresa May Coin
satoshimadness/">SatoshiMadness
elementrem/">Elementrem
aquariuscoin/">AquariusCoin
putin-classic/">Putin Classic
franko/">Franko
guncoin/">Guncoin
soilcoin/">SOILcoin
vector/">Vector
sling/">Sling
independent-money-system/">Independent M...
catcoin/">Catcoin
spacecoin/">SpaceCoin
dollarcoin/">Dollarcoin
secretcoin/">SecretCoin
token/">300 Token
x-coin/">X-Coin
oin/">DIBCOIN
bitcointx/">BitcoinTX
islacoin/">IslaCoin
hacker-gold/">Hacker Gold
cachecoin/">CacheCoin
sativacoin/">Sativacoin
evil-coin/">Evil Coin
bipcoin/">BipCoin
wmcoin/">WMCoin
aricoin/">Aricoin
wyvern/">Wyvern
paycon/">PayCon
spots/">Spots
bumbacoin/">BumbaCoin
coinonat/">Coinonat
dreamcoin/">Dreamcoin
bitcoin-21/">Bitcoin 21
tattoocoin/">Tattoocoin (S...
bitzeny/">Bitzeny
unrealcoin/">Unrealcoin
kurrent/">Kurrent
rimbit/">Rimbit
marscoin/">Marscoin
beatcoin/">Beatcoin
compucoin/">CompuCoin
bitcoinfast/">BitcoinFast
evotion/">Evotion
redcoin/">RedCoin
flavorcoin/">FlavorCoin
beavercoin/">BeaverCoin
ponzicoin/">PonziCoin
gapcoin/">Gapcoin
globaltoken/">GlobalToken
marijuanacoin/">Marijuanacoin
allsafe/">AllSafe
securecoin/">SecureCoin
tristar-coin/">Tristar Coin
gold-pressed-latinum/">Gold Pressed ...
ck-asset/">Qibuck Asset
popularcoin/">PopularCoin
impact/">Impact
plncoin/">PLNcoin
money/">Money
philosopher-stones/">Philosopher S...
ess-ethereum-token/">Useless Ether...
quatloo/">Quatloo
billarycoin/">BillaryCoin
kittehcoin/">Kittehcoin
jewels/">Jewels
uro/">Uro
bitcoin-planet/">Bitcoin Planet
arbit/">ARbit
vip-tokens/">VIP Tokens
warp/">WARP
debitcoin/">Debitcoin
agrolifecoin/">AgrolifeCoin
milocoin/">MiloCoin
halcyon/">Halcyon
urst/">UniBURST
hexx/">Hexx
destiny/">Destiny
gbcgoldcoin/">GBCGoldCoin
genstake/">G3N
mustangcoin/">MustangCoin
leacoin/">LeaCoin
tradecoin-v2/">Tradecoin
bios-crypto/">BiosCrypto
zayedcoin/">Zayedcoin
ronpaulcoin/">RonPaulCoin
healthywormcoin/">HealthyWormCoin
cryptoescudo/">CryptoEscudo
mindcoin/">MindCoin
creatio/">Creatio
global-tour-coin/">Global Tour Coin
ride-my-car/">Ride My Car
sooncoin/">SoonCoin
steps/">Steps
tagrcoin/">TAGRcoin
photon/">Photon
nevacoin/">NevaCoin
asset/">Dix Asset
wallet-builders-coin/">WalletBuilder...
virtualcoin/">VirtualCoin
cthulhu-offerings/">Cthulhu Offer...
pulse/">Pulse
ucoin/">UCoin
gamebet-coin/">GameBet Coin
cabbage/">Cabbage
benjirolls/">BenjiRolls
tajcoin/">TajCoin
artex-coin/">Artex Coin
cryptoworldx-token/">CryptoWorldX ...
blackstar/">Blackstar
bitquark/">BitQuark
zetamicron/">ZetaMicron
bbqcoin/">BBQCoin
bitcoal/">BitCoal
socialcoin-socc/">SocialCoin
metal-music-coin/">Metal Music Coin
ammo-rewards/">Ammo Rewards
high-voltage/">High Voltage
bnrtxcoin/">BnrtxCoin
digital-rupees/">Digital Rupees
songcoin/">SongCoin
orlycoin/">Orlycoin
vault-coin/">Vault Coin
osmiumcoin/">OsmiumCoin
luna-coin/">Luna Coin
torcoin-tor/">Torcoin
virtacoin/">Virtacoin
impulsecoin/">ImpulseCoin
dpay/">DPAY
neuro/">Neuro
dappster/">DAPPSTER
printerium/">Printerium
anarchistsprime/">AnarchistsPrime
vaperscoin/">VapersCoin
blazecoin/">BlazeCoin
letitride/">LetItRide
dollar-online/">Dollar Online
zonecoin/">Zonecoin
coin/">Coin(O)
fuzzballs/">FuzzBalls
xiaomicoin/">Xiaomicoin
bowscoin/">BowsCoin
crtcoin/">CRTCoin
project-x/">Project-X
coimatic-2/">Coimatic 2.0
biobar/">BioBar
ego/">EGO
cashcoin/">Cashcoin
posex/">PosEx
ibank/">iBank
jobscoin/">JobsCoin
save-and-gain/">Save and Gain
ner/">CCMiner
all/">Lex4All
xonecoin/">Xonecoin
antilitecoin/">Antilitecoin
litecred/">Litecred
argus/">Argus
concoin/">Concoin
tocean/">BurstOcean
shilling/">Shilling
bitvolt/">Bitvolt
1credit/">1CRedit
sydpak/">SydPak
magnum/">Magnum
speedcash/">Speedcash
geertcoin/">GeertCoin
rawcoin2/">Rawcoin
nodecoin/">NodeCoin
revenu/">Revenu
p7coin/">P7Coin
token/">JIO Token
mantracoin/">MantraCoin
selfiecoin/">Selfiecoin
ragon/">BTCDragon
enigma/">Enigma
themug/">MikeTheMug
environ/">Environ
pizzacoin/">PizzaCoin
elysium/">Elysium
californium/">Californium
powercoin/">Powercoin
future-digital-currency/">Future Digita...
digital-credits/">Digital Credits
digital-money-bits/">Digital Money...
caliphcoin/">CaliphCoin
xenixcoin/">Xenixcoin
internet-of-people/">Internet of P...
fedorashare/">FedoraShare
infchain/">InfChain
pura/">Pura
golos-gold/">Golos Gold
/">MCAP
fargocoin/">Fargocoin
dynamiccoin/">DynamicCoin
atbcoin/">ATBCoin
ethereum-dark/">Ethereum Dark
buzzcoin/">BuzzCoin
asset-backed-coin/">Asset Backed ...
ra/">Centra
ntraland/">Decentraland
techshares/">TechShares
ix/">Tronix
a-loyalty-points/">Moeda Loyalty...
/">Hive
e-air/">Sphre AIR
bagcoin/">BagCoin
gulfcoin/">GulfCoin
lepaoquan/">Lepaoquan
jcoin-x/">Storjcoin X
oken/">UG Token
clubcoin/">ClubCoin
sigmacoin/">SIGMAcoin
aureus/">Aureus
ganjacoin/">GanjaCoin
odao/">NeuroDAO
y/">bitqy
nt/">iQuant
wa-space/">WA Space
falcoin/">Falcoin
alpacoin/">AlpaCoin
pabyosi-coin-special/">Pabyosi Coin ...
s-social/">Nexus Social
morningstar-payments/">MorningStar
namocoin/">NamoCoin
ina/">OX Fina
regacoin/">Regacoin
t-bitcoin-capital/">First Bitcoin...
paccoin/">Paccoin
ulatech/">Ulatech
bitcoin-unlimited/">Bitcoin Unlim...
bitcloud/">Bitcloud
geysercoin/">GeyserCoin
pirate-blocks/">Pirate Blocks
digitalprice/">DigitalPrice
gaycoin/">GAY Money
/">Ergo
mind-gene/">Mind Gene
deuscoin/">DeusCoin
vechain/">VeChain
rse-token/">Indorse Token
terranova/">TerraNova
leviarcoin/">LeviarCoin
tyrocoin/">Tyrocoin
uncoin/">UNCoin
masternodecoin/">Masternodecoin
btcgold/">BTCGold
quotient/">Quotient
coin/">Facecoin
stronghands/">StrongHands
hbcoin/">HBCoin
teracoin/">TeraCoin
zilbercoin/">Zilbercoin
bitok/">Bitok
global-business-revolution/">Global Busine...
bitfid/">BITFID
ident-trump/">President Trump
wowecoin/">Wowecoin
edrcoin/">EDRCoin
/">BRAT
amsterdamcoin/">AmsterdamCoin
kchain-index/">Blockchain Index
num/">Bolenum
rublebit/">RubleBit
peacecoin/">Peacecoin
betacoin/">BetaCoin
t-coin/">T-coin
neptune-classic/">Neptune Classic
opal/">Opal
unioncoin/">GoldUnionCoin
fuda-energy/">Fuda Energy
cyder/">Cyder
digitalfund/">Digitalfund
asiccoin/">AsicCoin
flash/">Flash
eeyes/">SnakeEyes
landcoin/">LandCoin
universalroyalcoin/">UniversalRoya...
sakuracoin/">Sakuracoin
sharkcoin/">Sharkcoin
braincoin/">Braincoin
9coin/">9COIN
ur/">UR
atmcoin/">ATMCoin
us/">Nexxus
gameleaguecoin/">GameLeagueCoin
xtd-coin/">XTD Coin
coupecoin/">Coupecoin
cubits/">Cubits
halloween-coin/">Halloween Coin
abitcoinfund/">Alphabit
fibocoins/">FiboCoins
bestchain/">BestChain
yescoin/">Yescoin
rabbitcoin/">RabbitCoin
yogold/">Yogold
motocoin/">Motocoin
fireflycoin/">FireFlyCoin
batcoin/">BatCoin
linkedcoin/">LinkedCoin
avatarcoin/">AvatarCoin
paypeer/">PayPeer
ean/">Protean
birds/">Birds
animecoin/">Animecoin
adcoin/">AdCoin
tly/">Suretly
advanced-internet-blocks/">Advanced Inte...

In [220]:
#lol